### ISSUE TITLE
Tree trace output by revbayes is mixed up

### ISSUE THREAD

**Issue by Boussau** [revbayes/revbayes#10]
Hi, 
After inference of timetrees under a relaxed clock model, several of my runs produced traces that could not be read by readTreeTrace. Looking into one file, I discovered that the trees had been mixed up in the output at some point. In particular: 
28090   -178.302        734.53  -912.831        (((((((T_15[&index=102]:17.476780[&branch_rates=0.00861434],T_71[&index=101]:17.476780[&branch_rates=0.00771089])[&index=103]:0.457556[&branch_rates=0.00616907],(T_95[&index=100]:15.363817[&branch_rates=0.0115288],(T_76[&index=99]:11.417745[&branch_rates=0.0145349],T_83[&index=98]:11.417745[&branch_rates=0.00625412])[&index=104]:3.946072[&branch_
rates=0.00969361])[&index=105]:2.570519[&branch_rates=0.00516328])[&index=106]:8.540850[&branch_rates=0.00480853],T_46[&index=97]:26.475186[&branch_rates=0.00148403])[&index=107]:0.206725[&branch_rates=0.00783237],(T_30[&index=96]:26.405123[&branch_rates=0.00100268],(T_66[&index=95]:23.065086[&branch_rates=0.00227616],T_64[&index=94]:23.065086[&branch_rates=0.00153863])[&index=108]:3.340037[&b
ranch_rates=0.00675175])[&index=109]:0.276787[&branch_rates=0.0130544])[&index=110]:16.417341[&branch_rates=0.000734319],(((((T_2[&index=93]:32.940691[&branch_rates=0.000490121],((T_40[&index=92]:25.520926[&branch_rates=0.00195713],(((T_85[&index=91]:21.829709[&branch_rates=0.00305157],(T_62[&index=90]:8.084859[&branch_rates=0.00657228],T_27[&index=89]:8.084859[&branch_rates=0.00719339])[&inde
x=111]:13.744850[&branch_rates=0.000160385])[&index=112]:0.653400[&branch_rates=0.0146867],T_23[&index=88]:22.483109[&branch_rates=0.00222961])[&index=113]:0.754413[&branch_rates=0.00599838],T_93[&index=87]:23.237522[&branch_rates=0.00173152])[&index=114]:2.283403[&branch_rates=0.0106049])[&index=115]:7.171200[&branch_rates=0.0032859],T_74[&index=86]:32.692126[&branch_rates=0.00119532])[&index
=116]:0.248565[&branch_rates=0.0402558])[&index=117]:1.886978[&branch_rates=0.012777],T_36[&index=85]:34.827668[&branch_rates=0.00216848])[&index=118]:1.693601[&branch_rates=0.0249896],(((T_73[&index=84]:6.601641[&branch_rates=0.00974482],T_22[&index=83]:6.601641[&branch_rates=0.0122902])[&index=119]:6.870819[&branch_rates=0.0041336],T_35[&index=82]:13.472460[&branch_rates=0.00240727])[&index=
120]:6.525287[&branch_rates=0.00389882],(((T_14[&index=81]:14.350385[&branch_rates=0.0019672],T_87[&index=80]:14.350385[&branch_rates=0.00397351])[&index=121]:1.666199[&branch_rates=0.0299434],T_56[&index=79]:16.016584[&branch_rates=0.00273606])[&index=122]:0.165132[&branch_rates=0.00290259],T_67[&index=78]:16.181716[&branch_rates=0.00245303])[&index=123]:3.816031[&branch_rates=0.00236202])[&i
ndex=124]:16.523522[&branch_rates=0.000795396])[&index=125]:1.270366[&branch_rates=0.0408609],(((T_25[&index=77]:8.571542[&branch_rates=0.00303735],T_55[&index=76]:8.571542[&branch_rates=0.00757355])[&index=126]:6.005340[&branch_rates=0.00094167],T_45[&index=75]:1
4.576883[&branch_rates=0.00296512])[&index=127]:3.793832[&branch_rates=0.00346369],((((T_47[&index=74]:8.782162[&branch_rates=0.00330468],(T_24[&index=73]:3.487858[&branch_rates=0.0101289],T_101[&index=72]:3.487858[&branch_rates=0.0124081])[&index=128]:5.294304[&branch_rates=0.0106251])[&index=129]:3.407345[&branch_rates=0.0152449],T_70[&index=71]:12.189507[&branch_rates=0.00655078])[&index=130]:3.611939[&branch_rates=0.00492867],T_97[&index=70]:15.801446[&branch_rates=0.00608629])[&index=131]:0.439339[&branch_rates=0.0250527],T_78[&index=69]:16.240785[&branch_rates=0.00562319])[&index=132]:2.129930[&branch_rates=0.00359208])[&index=133]:19.420920[&branch_rates=0.000629051])[&index=134]:4.053701[&branch_rates=0.0168563],T_21[&index=68]:41.845336[&branch_rates=0.00217469])[&index=135]:1.253915[&branch_rates=0.01797])[&index=136]:1.551521[&branch_rates=0.0105662],T_63[&index=67]:44.650773[&branch_rates=0.000150383])[&index=137]:4.771134[&branch_rates=0.000800398],(((((T_28[&index=66]:11.571756[&branch_rates=0.000295636],T_75[&index=65]:11.571756[&branch_rates=0.0043884])[&index=138]:8.546574[&branch_rates=0.00603148],(T_91[&index=64]:14.560727[&branch_rates=0.00101018],T_16[&index=63]:14.560727[&branch_rates=0.00175181])[&index=139]:5.557603[&branch_rates=0.0019867])[&index=140]:8.980936[&branch_rates=0.00189593],((T_53[&index=62]:22.786275[&branch_rates=0.00223355],((T_33[&index=61]:7.195371[&branch_rates=0.00517529],T_8[&index=60]:7.195371[&branch_rates=0.00511265])[&index=141]:14.508743[&branch_rates=0.00130812],((T_61[&index=59]:19.009332[&branch_rates=0.00488583],(((T_20[&index=58]:11.613060[&branch_rates=0.0100688],T_59[&index=57]:11.613060[&branch_rates=0.00352617])[&index=142]:1.087369[&branch_rates=0.00662215],T_0[&index=56]:12.700429[&branch_rates=0.000240673])[&index=143]:4.284587[&branch_rates=0.00848315],T_100[&index=55]:16.985015[&branch_rates=0.000765496])[&index=144]:2.024316[&branch_rates=0.0173985])[&index=145]:2.068612[&branch_rates=0.0201115],T_11[&index=54]:21.077944[&branch_rates=0.00230226])[&index=146]:0.626170[&branch_rates=0.0171764])[&index=147]:1.082161[&branch_rates=0.00420246])[&index=148]:4.174037[&branch_rates=0.00640056],(T_5[&index=53]:9.491391[&branch_rates=0.00349982],T_68[&index=52]:9.491391[&branch_rates=0.011153])[&index=149]:17.468921[&branch_rates=0.000655473])[&index=150]:2.138953[&branch_rates=0.0221398])[&index=151]:3.548471[&branch_rates=0.00316411],(((T_4[&index=51]:29.570284[&branch_rates=0.00272761],T_39[&index=50]:29.570284[&branch_rates=0.00229018])[&index=152]:0.575734[&branch_rates=0.0200985],T_17[&index=49]:30.146018[&branch_rates=0.00140066])[&index=153]:1.340792[&branch_rates=0.00797414],((((((T_92[&index=48]:3.450402[&branch_rates=0.0173715],T_52[&index=47]:3.450402[&branch_rates=0.0202783])[&index=154]:14.533416[&branch_rates=0.00230322],((T_41[&index=46]:3.768427[&branch_rates=0.0152223],T_44[&index=45]:3.768427[&branch_rates=0.0101388])[&index=155]:10.691994[&branch_rates=0.00151065],(T_72[&index=44]:12.268047[&branch_rates=0.00262],T_69[&index=43]:12.268047[&branch_rates=0.0105474])[&index=156]:2.192374[&branch_rates=0.00709059])[&index=157]:3.523397[&branch_rates=0.0174381])[&index=158]:10.210811[&branch_rates=0.00565148],(((T_26[&index=42]:5.558365[&branch_rates=0.00130709],T_6[&index=41]:5.558365[&branch_rates=0.00743927])[&index=159]:3.929391[&branch_rates=0.0110306],T_98[&index=40]:9.487756[&branch_rates=0.00144499])[&index=160]:8.978562[&branch_rates=0.00740869],(((T_60[&index=39]:13.650985[&branch_rates=0.000828643],(T_13[&index=38]:9.152876[&branch_rates=0.027032],T_81[&index=37]:9.152876[&branch_rates=0.0228898])[&index=161]:4.498109[&branch_rates=0.0161642])[&index=162]:0.958314[&branch_rates=0.0104265],T_48[&index=36]:14.609299[&branch_rates=0.0134106])[&index=163]:2.852772[&branch_rates=0.00374528],(T_42[&index=35]:14.934530[&branch_rates=0.0101777],(T_7[&index=34]:14.400663[&branch_rates=0.0101234],T_18[&index=33]:14.400663[&branch_rates=0.00287002])[&index=164]:0.533867[&branch_rates=0.024729])[&index=165]:2.527541[&branch_rates=0.0140246])[&index=166]:1.004247[&branch_rates=0.0369492])[&index=167]:9.728311[&branch_rates=0.00753387])[&index=168]:0.361005[&branch_rates=0.0150819],(T_94[&index=32]:21.142244[&branch_rates=0.000949582],(((T_12[&index=31]:10.588492[&branch_rates=0.0238349],T_57[&index=30]:10.588492[&branch_rates=0.0262251])[&index=169]:7.374775[&branch_rates=0.0133436],(T_86[&index=29]:12.268195[&branch_rates=0.0130278],(T_19[&index=28]:9.976752[&branch_rates=0.0147601],T_96[&index=27]:9.976752[&branch_rates=0.0205266])[&index=170]:2.291442[&branch_rates=0.00565224])[&index=171]:5.695072[&branch_rates=0.0119489])[&index=172]:1.595681[&branch_rates=0.00856201],(T_31[&index=26]:17.788243[&branch_rates=0.00772443],(T_80[&index=25]:12.036131[&branch_rates=0.0116468],T_77[&index=24]:12.036131[&branch_rates=0.0062086])[&index=173]:5.752112[&branch_rates=0.010367])[&index=174]:1.770705[&branch_rates=0.0304022])[&index=175]:1.583296[&branch_rates=0.0490682])[&index=176]:7.413391[&branch_rates=0.0133533])[&index=177]:1.804402[&branch_rates=0.0116226],((T_89[&index=23]:27.796750[&branch_rates=0.00232227],(T_29[&index=22]:22.168838[&branch_rates=0.00403292],((((T_82[&index=21]:11.078006[&branch_rates=0.0122296],(T_38[&index=20]:10.281170[&branch_rates=0.0168968],T_79[&index=19]:10.281170[&branch_rates=0.0203959])[&index=178]:0.796835[&branch_rates=0.00948514])[&index=179]:1.321265[&branch_rates=0.012641],((T_1[&index=18]:10.038956[&branch_rates=0.00310186],T_50[&index=17]:10.038956[&branch_rates=0.00296504])[&index=180]:1.529709[&branch_rates=0.00942008],T_54[&index=16]:11.568666[&branch_rates=0.0137556])[&index=181]:0.830605[&branch_rates=0.0135499])[&index=182]:1.332007[&branch_rates=0.0105756],(T_84[&index=15]:11.044574[&branch_rates=0.00764622],T_32[&index=14]:11.044574[&branch_rates=0.01055])[&index=183]:2.686704[&branch_rates=0.00526411])[&index=184]:2.745531[&branch_rates=0.0332441],(T_43[&index=13]:10.528490[&branch_rates=0.0119616],T_90[&index=12]:10.528490[&branch_rates=0.0321986])[&index=185]:5.948319[&branch_rates=0.0103703])[&index=186]:5.692029[&branch_rates=0.00664695])[&index=187]:5.627912[&branch_rates=0.0276038])[&index=188]:0.662344[&branch_rates=0.0548709],(T_58[&index=11]:21.275173[&branch_rates=0.0146464],T_34[&index=10]:21.275173[&branch_rates=0.00607215])[&index=189]:7.183922[&branch_rates=0.00186827])[&index=190]:1.900942[&branch_rates=0.00261478])[&index=191]:1.060808[&branch_rates=0.022549],(((T_3[&index=9]:8.093033[&branch_rates=0.0270316],T_99[&index=8]:8.093033[&branch_rates=0.0105797])[&index=192]:11.323130[&branch_rates=0.00579855],T_9[&index=7]:19.416162[&branch_rates=0.00193363])[&index=193]:9.541029[&branch_rates=0.00912068],((T_65[&index=6]:11.386683[&branch_rates=0.00448358],T_10[&index=5]:11.386683[&branch_rates=0.0114745])[&index=194]:7.716955[&branch_rates=0.00596921],(T_37[&index=4]:11.876765[&branch_rates=0.0141956],T_51[&index=3]:11.876765[&branch_rates=0.017029])[&index=195]:7.226874[&branch_rates=0.00371658])[&index=196]:9.853553[&branch_rates=0.00413128])[&index=197]:2.463653[&branch_rates=0.0518586])[&index=198]:0.065966[&branch_rates=0.0148937])[&index=199]:1.160927[&branch_rates=0.00898712])[&index=200]:9.863564[&branch_rates=0.00144977],(T_49[&index=2]:37.895215[&branch_rates=0.00670957],T_88[&index=1]:37.895215[&branch_rates=0.010372])[&index=201]:4.616085[&branch_rates=0.00222538])[&index=202]:6.910607[&branch_rates=0.000966662])[&index=203]:0.000000;
28120   -214.78 709.955 -924.735        (((((((T_15[&index=102]:17.967903[&branch_rates=0.00782325],T_71[&index=101]:17.967903[&branch_rates=0.00785779])[&index=103]:3.501896[&branch_rates=0.00255076],(T_95[&index=100]:15.141166[&branch_rates=0.0124016],(T_76[&index=99]:10.259769[&branch_rates=0.0146567],T_83[&index=98]:10.259769[&branch_rates=0.00519336])[&index=104]:4.881396[&branch_rates=0.00707874])[&index=105]:6.328633[&branch_rates=0.00182888])[&index=106]:9.900828[&branch_rates=0.0034607],T_46[&index=97]:31.370626[&branch_rates=0.00102262])[&index=107]:0.201599[&branch_rates=0.00808449],(T_30[&index=96]:29.558402[&branch_rates=0.00102986],(T_66[&index=95]:26.704375[&branch_rates=0.0026098],T_64[&index=94]:26.704375[&branch_rates=0.00133333])[&index=108]:2.854027[&branch_rates=0.00546023])[&index=109]:2.013823[&branch_rates=0.00228057])[&index=110]:16.522087[&branch_rates=0.000902775],(((((T_2[&index=93]:34.457117[&branch_rates=0.000768211],((T_40[&index=92]:30.860598[&branch_rates=0.00116657],(((T_85[&index=91]:27.656867[&branch_rates=0.00271009],(T_62[&index=90]:9.529847[&branch_rates=0.00559122],T_27[&index=89]:9.529847[&branch_rates=0.00525962])[&index=111]:18.127020[&branch_rates=0.000373102])[&index=112]:1.006054[&branch_rates=0.0163782],T_23[&index=88]:28.662921[&branch_rates=0.00184445])[&index=113]:0.191302[&branch_rates=0.017133],T_93[&index=87]:28.854223[&branch_rates=0.00163602])[&index=114]:2.006375[&branch_rates=0.0138839])[&index=115]:3.051038[&branch_rates=0.0084725],T_74[&index=86]:33.911636[&branch_rates=0.00107256])[&index=116]:0.545481[&branch_rates=0.0153955])[&index=117]:1.122731[&branch_rates=0.0134206],T_36[&index=85]:35.579848[&branch_rates=0.0020945])[&index=118]:1.650218[&branch_rates=0.0193182],(((T_73[&index=84]:8.930187[&branch_rates=0.0065918],T_22[&index=83]:8.930187[&branch_rates=0.00848015])[&index=119]:4.697399[&branch_rates=0.00803774],T_35[&index=82]:13.627587[&branch_rates=0.00182104])[&index=120]:14.000347[&branch_rates=0.00186847],(((T_14[&index=81]:11.066774[&branch_rates=0.00246086],T_87[&index=80]:11.066774[&branch_rates=0.00414485])[&index=121]:3.767039[&branch_rates=0.0115237],T_56[&index=79]:14.833813[&branch_rates=0.00298765])[&index=122]:10.642160[&branch_rates=0.000482009],T_67[&index=78]:25.475973[&branch_rates=0.00138768])[&index=123]:2.151961[&branch_rates=0.00760732])[&index=124]:9.602132[&branch_rates=0.00128506])[&index=125]:2.676141[&branch_rates=0.0160896],(((T_25[&index=77]:12.505168[&branch_rates=0.00329447],T_55[&index=76]:12.505168[&branch_rates=0.00540862])[&index=126]:7.774288[&branch_rates=0.000976218],T_45[&index=75]:20.279456[&branch_rates=0.0015128])[&index=127]:3.732035[&branch_rates=0.00250955],((((T_47[&index=74]:7.411029[&branch_rates=0.00502543],(T_24[&index=73]:1.527146[&branch_rates=0.0199504],T_101[&index=72]:1.527146[&branch_rates=0.0239771])[&index=128]:5.883883[&branch_rates=0.00787836])[&index=129]:3.947793[&branch_rates=0.0144264],T_70[&index=71]:11.358822[&branch_rates=0.00541055])[&index=130]:4.898734[&branch_rates=0.00292051],T_97[&index=70]:16.257556[&branch_rates=0.00637179])[&index=131]:2.250146[&branch_rates=0.00726571],T_78[&index=69]:18.507702[&branch_rates=0.00533111])[&index=132]:5.503789[&branch_rates=0.00200505])[&index=133]:15.894716[&branch_rates=0.000655313])[&index=134]:4.937626[&branch_rates=0.00903708],T_21[&index=68]:44.843833[&branch_rates=0.00160598])[&index=135]:3.250480[&branch_rates=0.00926176])[&index=136]:1.862737[&branch_rates=0.00511415],T_63[&index=67]:49.957050[&branch_rates=9.4135e-05])[&index=137]:0.594588[&branch_rates=0.00222733],(((((T_28[&index=66]:7.032290[&branch_rates=0.000955511],T_75[&index=65]:7.032290[&branch_rates=0.00464209])[&index=138]:9.303682[&branch_rates=0.00579926],(T_91[&index=64]:12.406872[&branch_rates=0.00124148],T_16[&index=63]:12.406872[&branch_rates=0.00119055])[&index=139]:3.929100[&branch_rates=0.00188822])[&index=140]:15.779799[&branch_rates=0.000291674],((T_53[&index=62]:25.998982[&branch_rates=0.00263039],((T_33[&index=61]:8.355497[&branch_rates=0.00252319],T_8[&index=60]:8.355497[&branch_rates=0.00454011])[&index=141]:16.326419[&branch_rates=0.000880119],((T_61[&index=59]:23.494338[&branch_rates=0.00430879],(((T_20[&index=58]:12.299422[&branch_rates=0.0101818],T_59[&index=57]:12.299422[&branch_rates=0.00379021])[&index=142]:1.063343[&branch_rates=0.00991011],T_0[&index=56]:13.362765[&branch_rates=0.000526402])[&index=143]:7.766901[&branch_rates=0.00307686],T_100[&index=55]:21.129666[&branch_rates=0.000653452])[&index=144]:2.364672[&branch_rates=0.0186922])[&index=145]:0.868784[&branch_rates=0.0573177],T_11[&index=54]:24.363122[&branch_rates=0.00205174])[&index=146]:0.318794[&branch_rates=0.0204227])[&index=147]:1.317066[&branch_rates=0.00309627])[&index=148]:3.060839[&branch_rates=0.0108599],(T_5[&index=53]:9.597838[&branch_rates=0.0030665],T_68[&index=52]:9.597838[&branch_rates=0.0136917])[&index=149]:19.461983[&branch_rates=0.000538373])[&index=150]:3.055950[&branch_rates=0.0197141])[&index=151]:1.689724[&branch_rates=0.0103856],(((T_4[&index=51]:31.364669[&branch_rates=0.00307601],T_39[&index=50]:31.364669[&branch_rates=0.00204359])[&index=152]:2.154512[&branch_rates=0.00647371],T_17[&index=49]:33.519181[&branch_rates=0.000953464])[&index=153]:0.224851[&branch_rates=0.0381203],((((((T_92[&index=48]:2.420360[&branch_rates=0.0160773],T_52[&index=47]:2.420360[&branch_rates=0.0281908])[&index=154]:15.827260[&branch_rates=0.00191128],((T_41[&index=46]:2.726775[&branch_rates=0.0236273],T_44[&index=45]:2.726775[&branch_rates=0.0135408])[&index=155]:11.049321[&branch_rates=0.00193148],(T_72[&index=44]:9.358719[&branch_rates=0.00337706],T_69[&index=43]:9.358719[&branch_rates=0.0117929])[&index=156]:4.417376[&branch_rates=0.00404721])[&index=157]:4.471524[&branch_rates=0.0101567])[&index=158]:9.106731[&branch_rates=0.00385226],(((T_26[&index=42]:4.199577[&branch_rates=0.00373616],T_6[&index=41]:4.199577[&branch_rates=0.00739009])[&index=159]:3.025492[&branch_rates=0.0143774],T_98[&index=40]:7.225069[&branch_rates=0.000799657])[&index=160]:14.735061[&branch_rates=0.00490982],(((T_60[&index=39]:14.074038[&branch_rates=0.00104095],(T_13[&index=38]:10.381777[&branch_rates=0.0227677],T_81[&index=37]:10.381777[&branch_rates=0.0190885])[&index=161]:3.692261[&branch_rates=0.0212911])[&index=162]:0.916482[&branch_rates=0.0195328],T_48[&index=36]:14.990520[&branch_rates=0.0134965])[&index=163]:1.716784[&branch_rates=0.00639537],(T_42[&index=35]:12.660652[&branch_rates=0.0105467],(T_7[&index=34]:12.071548[&branch_rates=0.0116648],T_18[&index=33]:12.071548[&branch_rates=0.00322155])[&index=164]:0.589104[&branch_rates=0.014432])[&index=165]:4.046652[&branch_rates=0.00826207])[&index=166]:5.252826[&branch_rates=0.0127786])[&index=167]:5.394220[&branch_rates=0.0135292])[&index=168]:2.447002[&branch_rates=0.00189449],(T_94[&index=32]:23.709203[&branch_rates=0.000677964],(((T_12[&index=31]:10.001733[&branch_rates=0.0203896],T_57[&index=30]:10.001733[&branch_rates=0.0293973])[&index=169]:11.128811[&branch_rates=0.00694875],(T_86[&index=29]:13.374686[&branch_rates=0.013834],(T_19[&index=28]:10.951355[&branch_rates=0.0132756],T_96[&index=27]:10.951355[&branch_rates=0.0199377])[&index=170]:2.423331[&branch_rates=0.000359165])[&index=171]:7.755858[&branch_rates=0.00909362])[&index=172]:1.169440[&branch_rates=0.0192492],(T_31[&index=26]:18.137626[&branch_rates=0.00656547],(T_80[&index=25]:12.073142[&branch_rates=0.00993177],T_77[&index=24]:12.073142[&branch_rates=0.00627354])[&index=173]:6.064484[&branch_rates=0.0118337])[&index=174]:4.162359[&branch_rates=0.00742315])[&index=175]:1.409218[&branch_rates=0.0444718])[&index=176]:6.092150[&branch_rates=0.0156734])[&index=177]:2.576999[&branch_rates=0.0068803],((T_89[&index=23]:31.415050[&branch_rates=0.00281165],(T_29[&index=22]:26.791426[&branch_rates=0.00408021],((((T_82[&index=21]:13.897574[&branch_rates=0.00787417],(T_38[&index=20]:12.865377[&branch_rates=0.012054],T_79[&index=19]:12.865377[&branch_rates=0.0171812])[&index=178]:1.032197[&branch_rates=0.00778621])[&index=179]:1.280576[&branch_rates=0.0100175],((T_1[&index=18]:9.848513[&branch_rates=0.00409797],T_50[&index=17]:9.848513[&branch_rates=0.00310044])[&index=180]:2.908176[&branch_rates=0.00743665],T_54[&index=16]:12.756689[&branch_rates=0.0122515])[&index=181]:2.421461[&branch_rates=0.00335643])[&index=182]:0.727124[&branch_rates=0.0288971],(T_84[&index=15]:8.457035[&branch_rates=0.0104638],T_32[&index=14]:8.457035[&branch_rates=0.0132829])[&index=183]:7.448239[&branch_rates=0.00190765])[&index=184]:4.123740[&branch_rates=0.0209266],(T_43[&index=13]:16.321101[&branch_rates=0.00869434],T_90[&index=12]:16.321101[&branch_rates=0.0197392])[&index=185]:3.707913[&branch_rates=0.0149702])[&index=186]:6.762412[&branch_rates=0.00467725])[&index=187]:4.623624[&branch_rates=0.0330991])[&index=188]:0.323151[&branch_rates=0.0106847],(T_58[&index=11]:22.235571[&branch_rates=0.0136505],T_34[&index=10]:22.235571[&branch_rates=0.00590142])[&index=189]:9.502630[&branch_rates=0.0011081])[&index=190]:0.640150[&branch_rates=0.0337856])[&index=191]:1.193693[&branch_rates=0.0331159],(((T_3[&index=9]:9.738454[&branch_rates=0.0208346],T_99[&index=8]:9.738454[&branch_rates=0.00870224])[&index=192]:11.275551[&branch_rates=0.00664488],T_9[&index=7]:21.014005[&branch_rates=0.00158743])[&index=193]:8.108628[&branch_rates=0.0109999],((T_65[&index=6]:10.772282[&branch_rates=0.00365056],T_10[&index=5]:10.772282[&branch_rates=0.0138156])[&index=194]:7.205316[&branch_rates=0.00486989],(T_37[&index=4]:13.752966[&branch_rates=0.0117672],T_51[&index=3]:13.752966[&branch_rates=0.0156349])[&index=195]:4.224633[&branch_rates=0.00721898])[&index=196]:11.145034[&branch_rates=0.00435781])[&index=197]:4.449412[&branch_rates=0.0343587])[&index=198]:0.171988[&branch_rates=0.0080281])[&index=199]:0.061462[&branch_rates=0.0342359])[&index=200]:8.540371[&branch_rates=0.0016105],(T_49[&index=2]:33.889176[&branch_rates=0.00812741],T_88[&index=1]:33.889176[&branch_rates=0.0107983])[&index=201]:8.456690[&branch_rates=0.00158329])[&index=202]:8.205771[&branch_rates=0.00122542])[&index=203]:0.000000;
x=203]:0.000000;

This occurs with both rb-mpi and rb. I built my version a while ago:
RevBayes version (1.0.12)
Build from dev_boussau (8f6956) on vendredi 6 décembre 2019, 17:46:02 (UTC+0100)

Any idea what's happening? Is it a bug that may have been corrected in a recent commit? An idea for a fix? Thanks very much!

**Comment by willpett** [comment]
What exactly is the error that you receive when reading the trace file? Can you provide the rev script you used to generate this trace?

**Comment by Boussau** [comment]
Hi Will, 
I think I have found and solved the problem, which was not really on the revbayes side, sorry... Thanks very much!
