### ISSUE TITLE
Static type conversion disconnects variables from the DAG

### ISSUE THREAD

**Issue by willpett** [revbayes/revbayes#101]
A variable whose type doesn't match a function argument exactly may sometimes be automatically converted to the appropriate type. The result of this type conversion is a new constant node with the same value as the original variable. When passing arguments by value, this works fine. However, when passing arguments by reference, this causes a problem, because replacing a variable with a constant will disconnect the variable from its original DAG node.

As an example, a `Natural` may always be converted to a `Real`. Therefore, the following code executes without error:
```
mu ~ dnPoisson(1)
x ~ dnNormal(mu, 1)
```
However, if you examine `mu`, which was a `Natural<stochastic>`, you'll see it has been replaced with a `Real<constant>`:
```
> str(mu)

   _variable     = mu
   _RevType      = Real
   _value        = 1
   _dagType      = Constant node
   _children     = [ x ]
```

In general, the rules for type conversion are fairly strict, so this doesn't come up very often.

However, when a function is called in a "static" context (either as part of a constant node assignment, or as a bare function call), the rules for type conversion are much more relaxed. This can cause all sorts of strange behavior.

For example, the following throws an error:
```
x ~ dnNormal(0,1)
sqrt(x)
mvSlide(x)
```
Here, `x` is a `Real<stochastic>` but has been converted to a `RealPos<constant>` by `sqrt`.

I'm not sure what the solution to this problem is. One idea is to simply hand off the DAG node to the new variable during conversion. But then the DAG node's value must also be converted, which might cause problems (e.g. with `Simplex` to `RealPos[]`, see #14). And anyway, the variable's type is permanently converted, which could cause other downstream side effects.

Maybe something along the lines of what @bredelings suggested in #99 would work, where all type conversion happens through deterministic conversion nodes? Or possibly relying on dedicated internal functions to do the domain checking.

**Comment by bredelings** [comment]
This issue seems helpful.  Regardless what solution is eventually chosen, it might be worth writing a document that 
* clearly specifies how the type system affects execution, and is affected by it.
* clearly specifies what the type system is supposed to allow and prohibit (e.g. `x ~ dnNormal(0,1) ; y ~ dnGamma(x,x)` would presumably be prohibited)
