### ISSUE TITLE
no function named 'taxa'

### ISSUE THREAD

**Issue by ghost** [revbayes/revbayes#101]
I'm just getting started with RevBayes. Didn't get too far.
I had no problems installing Beta 1.0.0 (2015-03-31), the Mac download
In trying to run the first example, I got this:

```
 Processing file "JukesCantor.Rev"
   Successfully read one character matrix from file 'primates_cytb.nex'
   Error:   No function named 'taxa'
   Error:   Problem processing line 23 in file "JukesCantor.Rev"
```

Line 23 in JukesCantor.Rev is

```
taxa <- data.taxa()
```

Any ideas? 
Thanks,
Dave

**Comment by hoehna** [comment]
Hi Dave,

it seems to me that you are using the old version. There should be a built
with version 1.0 beta 3 (or 2 at least).
The problem you are having arises because we renamed the function names()
to taxa() because we thought it makes more sense. You should be able to see
the newer use in th tutorial scripts online.

Please let me know if there are still problems or if we uploaded the wrong
files.


Sebastian

**Comment by davidcannatella** [comment]
Sebastian,

Thanks. I had solved this issue by downloading beta 3 and compiling it.
However I did find other incompatibilities. For example, the compiled pdf
manual with all the tutorials is different from the individual tutorial
pdfs, and the .rev scripts are different in some cases from what is in the
tutorial.

Also, the beta 3 version does not work with some of the .rev scripts, but I
managed to fix the problems. These typically were functions that were
misnamed. So I have beta 3 working OK for the scripts that I needed.

On the Google groups site I also posted about a problem with compiling the
mpi version. At the moment, that is my holdup.

I'm teaching Systematics this semester, and would like to introduce the
students to RevBayes.

Best,
Dave


On Tue, Dec 29, 2015 at 3:10 PM, Sebastian Höhna <notifications@github.com>
wrote:

> Hi Dave,
>
> it seems to me that you are using the old version. There should be a built
> with version 1.0 beta 3 (or 2 at least).
> The problem you are having arises because we renamed the function names()
> to taxa() because we thought it makes more sense. You should be able to see
> the newer use in th tutorial scripts online.
>
> Please let me know if there are still problems or if we uploaded the wrong
> files.
>
>
> Sebastian
>
>
> On Sunday, December 27, 2015, dcc1225 <notifications@github.com> wrote:
>
> > I'm just getting started with RevBayes Didn't get too far
> > I had no problems installing Beta 100 (2015-03-31), the Mac download
> > In trying to run the first example, I got this:
> >
> > Processing file "JukesCantorRev"
> > Successfully read one character matrix from file 'primates_cytbnex'
> > Error: No function named 'taxa'
> > Error: Problem processing line 23 in file "JukesCantorRev"
> >
> > Line 23 in JukesCantorRev is
> >
> > taxa <- datataxa()
> >
> > Any ideas?
> > Thanks,
> > Dave
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/revbayes/revbayes/issues/101>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/revbayes/revbayes/issues/101#issuecomment-167878013>.
>



-- 
David Cannatella
Department of Integrative Biology
Assoc. Chair for Biodiversity Collections
Patterson Labs, 2415 Speedway
University of Texas
Austin, Texas 78712
www.cannatellalab.org
512.453.1620 cell
