### ISSUE TITLE
build on Linux with GCC fails

### ISSUE THREAD

**Issue by stuckyb** [revbayes/revbayes#105]
Hello,

Building the latest version of the RevBayes sources (cloned from the GitHub repository) fails on XUbuntu with GCC 5.2.1.  The problem is that Boost.Thread fails to build with the error message "error: no matching function for call to 'call_once(...)'", which is evidently a known issue with Boost 1.55 and recent versions of GCC (e.g., [http://lists.freebsd.org/pipermail/freebsd-office/2015-February/002706.html](url)).

I downloaded the latest version of the boost sources (1.60.0), changed the relevant parts of regenerate.sh to point to the new boost sources instead of the provided 1.55 sources, and RevBayes compiled without a hitch.

So, I would suggest just updating the included boost sources to 1.60 instead of 1.55 so that the code compiles properly with recent versions of GCC.

Thanks!

-Brian Stucky (Florida Museum of Natural History)

**Comment by mlandis** [comment]
Thanks Brian. I verified the fix works with an Ubuntu VM and pushed the changes to the current master/development branches.
