### ISSUE TITLE
dnPhyloBrownianREML with NAs

### ISSUE THREAD

**Issue by jasminelmah** [revbayes/revbayes#105]
I am trying to infer a phylogeny from a continuous data set, which is NA rich, and I am using PhyloBrownianREML to compute likelihoods. My preliminary run failed. Can PhyloBrownianREML handle NAs? If not, is it possible to add this feature or is this incompatibility inherent in PhyloBrownianREML's algorithm?

**Comment by hoehna** [comment]
Yes, the current implementation does not handle missing data under Brownian
motion. We can add this feature and for the next release it will be ready
for you.


Sebastian

**Comment by jasminelmah** [comment]
Thank you, I'd appreciate this as a feature! I would be really excited to see what Rev Bayes can do with NA continuous data.
