### ISSUE TITLE
can't compile mpi version in Linux

### ISSUE THREAD

**Issue by drelo** [revbayes/revbayes#107]
I am using Ubuntu 16.04 I just installed open-mpi with 

`do apt-get install openmpi-bin openmpi-common openssh-client openssh-server libopenmpi1.10
libopenmpi-dbg libopenmpi-dev`

I am getting this error

`# andrelo at finestra in ~/revbayes-master/projects/cmake on git:master ✖︎ [15:48:54]
→ ./build.sh -mpi true  
/home/andrelo/revbayes-master/projects/cmake
Building boost libraries
you can turn this of with argument "-boost false"
Building Boost.Build engine with toolset gcc... tools/build/src/engine/bin.linuxx86_64/b2
Unicode/ICU support for Boost.Regex?... not found.
Generating Boost.Build configuration in project-config.jam...

Bootstrapping is done. To build, run:

```
./b2
```

To adjust configuration, edit 'project-config.jam'.
Further information:
- Command line help:
   ./b2 --help
- Getting started guide: 
   http://www.boost.org/more/getting_started/unix-variants.html
- Boost.Build documentation:
   http://www.boost.org/build/doc/html/index.html

Performing configuration checks

```
- 32-bit                   : no  (cached)
- 64-bit                   : yes (cached)
- arm                      : no  (cached)
- mips1                    : no  (cached)
- power                    : no  (cached)
- sparc                    : no  (cached)
- x86                      : yes (cached)
```

Building the Boost C++ Libraries.

```
- symlinks supported       : yes (cached)
- gcc visibility           : yes (cached)
- long double support      : yes (cached)
- has_icu builds           : yes (cached)
- lockfree boost::atomic_flag : yes (cached)
```

Component configuration:

```
- atomic                   : not building
- chrono                   : not building
- container                : not building
- context                  : not building
- coroutine                : not building
- coroutine2               : not building
- date_time                : building
- exception                : not building
- filesystem               : not building
- graph                    : not building
- graph_parallel           : not building
- iostreams                : not building
- locale                   : not building
- log                      : not building
- math                     : building
- mpi                      : not building
- program_options          : building
- python                   : not building
- random                   : not building
- regex                    : building
- serialization            : building
- signals                  : building
- system                   : not building
- test                     : not building
- thread                   : building
- timer                    : not building
- type_erasure             : not building
- wave                     : not building
```

...patience...
...patience...
...patience...
...found 3854 targets...

The Boost C++ Libraries were successfully built!

The following directory should be added to compiler include paths:

```
/home/andrelo/revbayes-master/boost_1_60_0
```

The following directory should be added to linker library paths:

```
/home/andrelo/revbayes-master/boost_1_60_0/stage/lib
```

Flags:

CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find MPI_C (missing: MPI_C_LIBRARIES MPI_C_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindMPI.cmake:614 (find_package_handle_standard_args)
  CMakeLists.txt:26 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/andrelo/revbayes-master/projects/cmake/CMakeFiles/CMakeOutput.log".
See also "/home/andrelo/revbayes-master/projects/cmake/CMakeFiles/CMakeError.log".
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find MPI_C (missing: MPI_C_LIBRARIES MPI_C_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindMPI.cmake:614 (find_package_handle_standard_args)
  CMakeLists.txt:26 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/andrelo/revbayes-master/projects/cmake/CMakeFiles/CMakeOutput.log".
See also "/home/andrelo/revbayes-master/projects/cmake/CMakeFiles/CMakeError.log".
Makefile:218: recipe for target 'cmake_check_build_system' failed
# andrelo at finestra in ~/revbayes-master/projects/cmake on git:master ✖︎ [15:50:19]

→ `

I couldn't find those .log files but I can provide any detail if needed. 

How could I fix this?

Thanks

**Comment by blackrim** [comment]
I have this problem as well. My solution was to compile with 
`-boost false` and `sudo apt-get` all the `libboost` libraries it needed (just letting it fail and then `sudo apt-get` the libraries it states are missing. Then it worked just fine. Hope that helps
