### ISSUE TITLE
mac executable requires boost dylib

### ISSUE THREAD

**Issue by mtholder** [revbayes/revbayes#111]
Perhaps this is explained in the docs and I just missed it, but the Mac exe from https://github.com/revbayes/revbayes/releases/download/1.1.0/RevBayes_OSX_1.1.0.zip is dynamically linked to boost. 

I'm using this in the context of a lab for a class, and students are getting dyld errors:

    dyld: Library not loaded: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
    Referenced from: /Users/Home/Path/To/RBParent/rb
    Reason: image not found
    Abort trap: 6 

would it be possible to get a a build that is statically linked?

thanks,
Mark

**Comment by mtholder** [comment]
or instructions on how to fix this in the easiest manner... I'm guessing `brew`, but it has been a while since I've been on Mac

**Comment by wadedismukes** [comment]
I am working on publishing docker containers in various linux distribution that would be an option for people who are having install issues. This may be using a sledgehammer to crack a nut though...

**Comment by bjoelle** [comment]
@mtholder as a temporary workaround, your students can install boost with `brew install boost` (assuming they have Homebrew)

**Comment by wadedismukes** [comment]
If you are interested in using docker. I have setup an ubuntu image: https://github.com/wadedismukes/revbayes-dockerfiles/packages/454570

To run:
`docker run --rm -it  docker.pkg.github.com/wadedismukes/revbayes-dockerfiles/revbayesdockerfiles:ubuntu-latest`

Which will open up a `rb` instance. 

This should work in macOS and windows 10 with docker desktop installed, or in ubuntu with docker CLI tools. I will say I have only tested this on windows 10 and in ubuntu subsystem for windows 10.

**Comment by willpett** [comment]
I've replaced the mac binary in the 1.1.0 release with a static-linked image.
