### ISSUE TITLE
How many data can revbayes handle?

### ISSUE THREAD

**Issue by xiekunwhy** [revbayes/revbayes#112]
Hi,
As we have entered the omic age and the marker(SNP) number have increase to Mb level.
I want to know how many marker can RevBayes handle (sample size : 100 or more) on a common PC?
Best wishes!

**Comment by hoehna** [comment]
Hi, for large datasets the bigger problem is the actual memory usage. On the RAXML page you find a nice formula of the minimum memory requirements for a dataset: http://sco.h-its.org/exelixis/web/software/raxml/
Be aware that RevBayes probably uses 3-times as much memory for likelihood computation shortcuts to safe computation time. If you have a large compute cluster at hand, the computation time and memory usage can be split amongst nodes/cores when using the MPI version of RevBayes.
