### ISSUE TITLE
Crash analysing continuous data

### ISSUE THREAD

**Issue by anne-marie-lyne** [revbayes/revbayes#113]
Hi there,

I am trying to use RevBayes to estimate phylogeny from continuous data. When working through the above tutorial (second bottom tutorial from http://revbayes.github.io/tutorials.html) I keep getting the following error

libc++abi.dylib: Pure virtual function called!
Abort trap: 6

after running this line

logmass ~ dnPhyloBrownianREML(psi, branchRates=1.0, siteRates=sigma, nSites=1)

I get the same error on both mac and linux using version RevBayes 1.0.1. I also get the same error using my own data and tree.

Can others reproduce this error?

Thanks,
Anne-Marie

**Comment by hoehna** [comment]
This problem is fixed with the release version 1.0.2.
