### ISSUE TITLE
seg fault with dnFreeK

### ISSUE THREAD

**Issue by bayesiancook** [revbayes/revbayes#115]
I get a segfault if I try to use a free rate matrix:

> rates <- [[0,1,1], [1,0,1], [1,1,0]]
> Q := fnFreeK(rates)
> Q
Segmentation fault: 11

of note, the seg fault occurs, not upon creating the matrix, but only when trying to print it out or to use it somehow.

Also, it works fine if I define Q as a constant:

> rates <- [[0,1,1], [1,0,1], [1,1,0]]
> Q <- fnFreeK(rates)
> Q
   [ [ -1.0000, 0.5000, 0.5000 ] ,
     [ 0.5000, -1.0000, 0.5000 ] ,
     [ 0.5000, 0.5000, -1.0000 ] ]

(but then I cannot make it depend on other parameters).

I am using the last version on the master branch.

best,

nicolas

**Comment by willpett** [comment]
This should be fixed on `development` (see #100). Hi Nicolas :)
