### ISSUE TITLE
Failed in installing Revbayes

### ISSUE THREAD

**Issue by astridlee** [revbayes/revbayes#117]
Hi, 

Revbayes Team,

I have been tried to install Revbayes in Linux as the tutorials that you suggested(https://revbayes.github.io/singularity/), while after coding "singularity run --app rb RevBayes_Singularity_1.1.0.simg", failed to install it, which shows --
ERROR  : Unknown image format/type: RevBayes_Singularity_1.1.0.simg
ABORT  : Retval = 255.

Could you give me a hand to help it out?

Best wishes,

Astrid

**Comment by astridlee** [comment]
Addition:

I tried to install it again but failed in compiling it this time, which showed " Could NOT find Boost (missing: Boost_INCLUDE_DIR regex program_options
  thread system filesystem date_time serialization) (Required is at least
  version "1.60.0")"  but I have already refer to my path into ./build.sh -boost_root /root/boost_1_71_0 -boost_lib /root/boost_1_71_0/stage/lib. 

I tried it for several times but still failed in installing. I'm really hope that you could give me a help. 

Best wishes, 

Astrid.

**Comment by njbooher** [comment]
What version of Singularity are you using?

```
singularity --version
```
