### ISSUE TITLE
Binomial probability with deterministic node does not work

### ISSUE THREAD

**Issue by niharikag** [revbayes/revbayes#120]
Code:
N <- 10
phi ~ dnBeta(1,1)
lambda <- 100
err = 0.001

for (n in 1:N){
prob[n] := phi*err
D[n] ~ dnPoisson(lambda)
B[n] ~ dnBinomial(prob[n],D[n])
}

Error:
 Processing file "binomial_test.Rev"
   Error:       Argument or label mismatch for function call.
   Provided call:
   dnBinomial (Natural<stochastic>,
               RealPos<deterministic> )

   Correct usage is:
   dnBinomial (Probability<any> p,
               Natural<any> n)
   Error:       Problem processing line 10 in file "binomial_test.Rev"

Thanks,
Niharika

**Comment by afmagee** [comment]
As discussed in the Google Group (https://groups.google.com/g/revbayes-users/c/m0crd4IbJ6M), due to Rev's typing the use of the `Probability()` function is required. With that, the code works. For example:

    N <- 10
    phi ~ dnBeta(1,1)
    lambda <- 100
    err = 0.001

    for (n in 1:N){
        prob[n] := Probability(phi*err)
    
        D[n] ~ dnPoisson(lambda)
        B[n] ~ dnBinomial(prob[n],D[n])
    }
