### ISSUE TITLE
append or add function for a vector would be very nice

### ISSUE THREAD

**Issue by mtholder** [revbayes/revbayes#125]
It would be nice if novice users didn't have to worry about keeping track of (for example) the next index in the move vector. If vector (in the RevLanguage) supported some equivalent of C++'s `push_back`, it would be easier for new users.

*Note*: this is particularly an issue because some tutorials use `++mvi` and others use `mvi++` to increment the move index

**Comment by jembrown** [comment]
@mtholder It appears that append is now available for vectors in the current version of the development branch. But I don't think it's used in the tutorials.
