### ISSUE TITLE
dnUniformNatural does not sample its upper limit

### ISSUE THREAD

**Issue by onmikula** [revbayes/revbayes#129]
Hello,
I have realized samples taken from dnUniformNatural did not include the upper limit.
It can be demonstrated as follows:

for (i in 1:100) {
     int[i] ~ dnUniformNatural(1, 3)
}
int

where 'int' consists of 1 and 2, instead of 1, 2 and 3.
I am using the version 1.0.8
Best,
O. Mikula

**Comment by jembrown** [comment]
Hi, it appears that this issue has now been fixed in the latest version on the development branch. It should be included in the next release of RevBayes. If it isn't, feel free to open another issue.
