### ISSUE TITLE
ordered Q matrix + variable coding crashes the program

### ISSUE THREAD

**Issue by eascarrunz** [revbayes/revbayes#13]
The following crashes RevBayes v.1.0.12 on Windows 10 without an error message:
```
spp <- v(taxon("a"), taxon("b"), taxon("c"), taxon("d"))
Psi ~ dnUniformTopologyBranchLength(spp, branchLengthDistribution=dnLognormal(2, 1))
Q <- fnOrderedRateMatrix(4)
phylo ~ dnPhyloCTMC(tree=Psi, Q=Q, type="Standard", coding="variable")
```
The program does not crash if I don't specify the coding as "variable", but when I to run the analysis with my empirical data set I get the following:

>    Drawing new initial states ...
>    Could not compute lnProb for node z_3states_ordered.
>    Standard character matrix with 50 taxa and 28 charact
> 
>    Drawing new initial states ...
>    Error:       Unable to find a starting state with computable probability after 1000 tries
>    Error:       Problem processing line 90 in file "analysis2.Rev"

At least that's not a crash, and it might be just a problem with my specific data.

PS: Sorry for for the duplicated posting with the Google forum, I realised after the fact that it was more pertinent to post the issue here.

**Comment by bjoelle** [comment]
crash confirmed on the latest development build

**Comment by wrightaprilm** [comment]
Hi all, looks like there's a bug in how the diagonal is generated and I'll try to get that patched up here quickly. In the meantime, @eascarrunz, there is a work-around for specifiying ordered matrices in the [supplementary morphology models tutorial](https://revbayes.github.io/tutorials/morph/morph_more.html). It's under the section 'Asymmetric Ordered', and I'm happy to answer questions on the tutorial. Thanks for filing this issue!
