### ISSUE TITLE
FBD tutorial: Assertion `0.0 <= sum and sum <= 1.00000000001' failed.

### ISSUE THREAD

**Issue by bredelings** [revbayes/revbayes#131]
If you compile revbayes assertions enabled, then you get an assertion failure when running this FBD tutorial:

https://revbayes.github.io/tutorials/fbd/fbd_specimen.html

The assertion looks like this:

```
> source("mcmc_CEFBDRP_Ranges.Rev")
   Processing file "mcmc_CEFBDRP_Ranges.Rev"
   Successfully read one character matrix from file 'data/bears_cytb.nex'
   Successfully read one character matrix from file 'data/bears_morphology.nex'
   Processing file "scripts/model_FBDRP.Rev"
   Processing of file "scripts/model_FBDRP.Rev" completed
   Processing file "scripts/model_UExp.Rev"
   Processing of file "scripts/model_UExp.Rev" completed
   Processing file "scripts/model_GTRG.Rev"
   Processing of file "scripts/model_GTRG.Rev" completed
   Processing file "scripts/model_Morph.Rev"
   Processing of file "scripts/model_Morph.Rev" completed
   Could not compute lnProb for node fbd_tree.
   (Parictis_montanus[&index=22]:17.670708,((((Ailurar...

rb-debug: ../../source/src/core/distributions/phylogenetics/substitution/PhyloCTMCSiteHomogeneous.h:258: void RevBayesCore::PhyloCTMCSiteHomogeneous<charType>::computeInternalNodeLikelihood(const RevBayesCore::TopologyNode&, size_t, size_t, size_t) [with charType = RevBayesCore::StandardState; size_t = long unsigned int]: Assertion `0.0 <= sum and sum <= 1.00000000001' failed.
Aborted
```

Inspecting this in gdb shows the following:
* the value of sum is about 1.05
* we are computing likelihoods at an internal node
* the transition probability matrix is 2x2
* the transition probability matrix has negative elements!!
```
(gdb) p this->transition_prob_matrices[mixture].getElement(0,0)
$13 = (double &) @0x555559a48210: 12219.377083219342
(gdb) p this->transition_prob_matrices[mixture].getElement(0,1)
$14 = (double &) @0x555559a48218: -12218.377083219342
(gdb) p this->transition_prob_matrices[mixture].getElement(1,0)
$15 = (double &) @0x555559a48220: -12218.377083219342
(gdb) p this->transition_prob_matrices[mixture].getElement(1,1)
$16 = (double &) @0x555559a48228: 12219.377083219342
```

So, it looks like this is for the morphology model.  I'm guessing something crazy is happening with the exponential of the Jukes Cantor rate matrix, and we didn't normalize it.  It that is the case, then we need to:
- set negative elements to 0
- renormalize rows to sum to 1

**Comment by bjoelle** [comment]
@bredelings are the assertions enabled on the github-actions build ? I'm getting the same issue on the FBD integration test `tests/test_FBD/`

**Comment by bredelings** [comment]
My memory was that they are explicitly disabled in the cmake builds, which I think is all except the windows build.  

Yeah, assertions should be disabled via this line in `CMakeLists.txt`
```
set(OPTIMIZATION_FLAGS "-O3 -DNDEBUG")
```

**Comment by bredelings** [comment]
@bjoelle I think that passing `-debug true` to `build.sh` should enable assertions on cmake.

**Comment by bredelings** [comment]
This bug seems to result from having startAge < endAge in `RateMatrix_JC::calculateTransitionProbabilities( )`:
```
             double t = rate * (startAge - endAge); 
```
This leads to a negative value for `t`.

**Comment by willpett** [comment]
It seems unsurprising to me that certain proposals may lead to a state where `startAge < endAge`, which is then rejected because the probability cannot be computed. Perhaps a certain proposal that is unique to the FBD tutorial is causing this behavior? Personally, I would just remove the assertion.

**Comment by bredelings** [comment]
Interesting - I had assumed that this was a bug, perhaps in the simulation procedure.

This type of bug has caused problems previously because the probability _could_ be computed and the move was _not_ rejected.  Specifically, if the row sum for a transition matrix is greater than 1, then we tend to get stuck on that state forever.

**Comment by bredelings** [comment]
It looks like the error occurs in simulating leaf sequences on the tree -- so presumably the simulated tree has negative branch lengths.

**Comment by bredelings** [comment]
It looks like a fix might include:
- fixing the tree simulation to avoid negative branch lengths
- making the jukes-cantor code do something like `t = std::max(t,0.0)`

That would allow tree moves to create trees with negative branch lengths, without triggering the assertion.

**Comment by willpett** [comment]
I see. In that case, I would suggest that instead of an assertion, the check should instead cause the likelihood to return -inf. That way, trees can have negative branch lengths, and be properly rejected. I could see setting the branch length to zero potentially masking the issue.

**Comment by bredelings** [comment]
> In any case, the tree probability computation should catch negative branch lengths. If it doesn't, then it will cause problems beyond this assertion.

So, maybe we should catch negative branch lengths in tree probability computations before calling updateTransitionProbabilities( ) and return -Inf.

This would allow keeping the current assertion, which would only be reached if branch lengths are non-negative.  We could then add `assert(t >= 0.0)` to the individual exponentiation routines, which would avoid masking the issue.  (`RateGenerator_Epoch.cpp` already throws an exception if (t + 1.0e-6 < 0.0).)

@willpett Are you against assertions in principle?  

I like assertions because they speed up debugging by catching errors closer to the point that they occur.  For example, it took a lot of hours of debugging to figure out the root cause of MCMC not mixing with the covarion model, and it took several months for someone to find the time to look into it.  If we had an assertion it might have been fixed months earlier.

@bjoelle Any thoughts?

**Comment by willpett** [comment]
I am not against assertions in principle, but they are not commonly or consistently used in RevBayes. In general, I think the convention is to throw `RbException`. A check that the transition probabilities sum to 1.0 does seem useful... However, I can imagine a perfectly valid move that may occasionally propose negative branch lengths. In this case, the proposal should just be rejected rather than throw an exception or fail an assertion so as not to derail the entire MCMC. Also, I don't really like the idea of multiple checks in multiple locations that have different and arbitrary precisions. I would at least place the check in a more generic location (e.g. in the base class of `PhyloCTMCSiteHomogeneous` or `RateGenerator` as you suggested).

**Comment by bredelings** [comment]
> However, I can imagine a perfectly valid move that may occasionally propose negative branch lengths. In this case, the proposal should just be rejected rather than throw an exception or fail an assertion so as not to derail the entire MCMC.

Hmm.  This bug seems orthogonal to that, since (i) it seems to be coming from a bug in the simulateTree routine and (ii) we can certainly perform checks for sane transition probabilities even with negative branch lengths.

That said, I can see how proposing negative branch lengths could work, but it seems like the question really is whether we _want_ to allow that.  As an alternative, we could require that proposals that lead to negative branch lengths are responsible for cleaning up after themselves.  Do we currently have any such moves?

In any case, one way to handle such moves would be to assign each move the responsibility of checking for negative branch lengths.  Right now it looks like we need to handle them in all the tree likelihoods.

> Also, I don't really like the idea of multiple checks in multiple locations that have different and arbitrary precisions. I would at least place the check in a more generic location (e.g. in the base class of PhyloCTMCSiteHomogeneous or RateGenerator as you suggested).

Multiple different precisions does seem problematic.  I personally would tend to require that probabilities are >= 0.0 so no precision is required.  But if we want a precision, we could define a global constant.

I think the benefit for assertions to debugging comes from complaining _early_ when we get into a nonsensical state.  While I don't think we want to perform the same check twice, I do think it can be good to check preconditions and postconditions at entry and exit from subroutines.  Such checks have the additional benefit of declaring the assumptions made about the parameters and the return value in written form.

**Comment by bredelings** [comment]
One other thing that comes up is how to simulate character data on trees with negative branch lengths.

**Comment by benmarwick** [comment]
Hello, I'm working through this same tutorial and finding the same error. I'm using RevBayes version 1.1.1 on OSX
(Build from master (rapture-588-gae00cc) on Thu Feb 11 15:28:28 CST 2021). Is there something I can change in the tutorial to workaround this, or should I wait for a fix in a future version? Thank you.

**Comment by willpett** [comment]
I've located the source of this error, at least with the current integration tests. Randomly a state is proposed in the course of running the FBD tutorial where the partial likelihoods at an internal node are all 0.0. Then, when the partial likelihoods are scaled using `AbstractPhyloCTMCSiteHomogeneous::scale`, the scaling factor is computed as `-log(0.0)` which leads to division by `+Inf` which generates `NaN`. This causes the assertion to fail (since `sum == NaN`).

In my view, it is perfectly legitimate to propose such a state where the partial likelihoods are smaller than the scaling can keep up with, leading to a likelihood that cannot be computed. In other words, the assertion is failing on a perfectly acceptable MCMC state, not catching a bug. Therefore, I propose that these assertions should be disabled. They are simply not specific enough to discriminate valid and invalid MCMC states.

**Comment by bredelings** [comment]
Hmm.... I agree that we should allow cases where the likelihood is `NaN`.  This means that we need to:
1. not fail assertions when probabilities are NaN
1. not crash when sampling ancestral states if the conditional likelihoods or transition probabilities are NaN
1. MCMC should not accept a move to a state where the probability is NaN

To fix the assertions, it works to change `assert(0.0 <= sum and sum <= 1.00000000001);` to `assert(std::isnan(sum) or (0.0 <= sum and sum <= 1.00000000001))`.

How about the other two issues?

**Comment by bredelings** [comment]
I suppose another question is... is there some way to improve the scaling?  But that is orthogonal to the assertion.

**Comment by willpett** [comment]
I just think we should relocate the checks for actual bugs to other locations where they are more specific and pertinent. For example, a check for negative branch lengths would be more useful in `updateTransitionProbabilities`. It doesn't seem to me like these assertions are actually checking for much.

**Comment by bredelings** [comment]
BTW, I think right now `-ffast-math` disables any NaN handling by asserting that we never see NaNs.  

Dave Swofford says that `-ffast-math` is too dangerous to use.  I found out from personal experience that he had a point, when some of my code began crashing on ARM chips (who knew!).  It was because the default behavior for NaNs was different on different systems.

Removing `-ffast-math` does produce a small slowdown, but if you use just a few flags from `-ffast-math` (specifically `-fno-math-errno -fno-signed-zeros`) then you don't lose any of the speed, and you get almost all of the IEEE math guarantees, so code on different architectures runs the same.

**Comment by willpett** [comment]
Re: `-ffast-math` I would be very cautious. I recently found that different implementations of `libm` were causing discrepancies in integration test output on different platforms. Therefore, I think we should be extra careful about conforming to IEEE 754.

**Comment by bredelings** [comment]
I thought we were using `-ffast-math`, but I was wrong -- we are only using it in `src/grammar/Makefile`.  It seems unnecessary there, but I assume does not affect the rest of the code.

**Comment by bredelings** [comment]
> It doesn't seem to me like these assertions are actually checking for much.

Are you saying that the check isn't very strong after you let NaNs through?  I think the deal is that as soon as we see an NaN anywhere, the likelihood is going to be NaN, and we must reject the proposed state.  But if we don't see an NaN, then it makes sense to check that things are not crazy.

This check caught the problems with the covarion models failing for large branch lengths, where the rows summed to like 10000 instead of summing to 1.  The revised assert would still catch that.

The checks also caught a case where the transition probabilities were negative, and it would still catch that.

What am I missing?

> I just think we should relocate the checks for actual bugs to other locations where they are more specific and pertinent. For example, a check for negative branch lengths would be more useful in `updateTransitionProbabilities`.

Waiting to respond here pending question about.

**Comment by bredelings** [comment]
> Re: `-ffast-math` I would be very cautious. I recently found that different implementations of `libm` were causing discrepancies in integration test output on different platforms. Therefore, I think we should be extra careful about conforming to IEEE 754.

BTW, does this mean that some of the platforms were non-conformant with IEEE 754?

**Comment by willpett** [comment]
No, not technically. The standard actually only requires that the arithmetic is accurate to within 5ul. So having different `libm` implementations can be conformant, while not strictly deterministic across platforms. But our integration tests require absolute determinism. So I just think we just shouldn't be playing fast and loose with optimizations like `-ffast-math` that can explicitly lead to non-conformant machine code when even conformant code breaks our tests.

**Comment by willpett** [comment]
> Are you saying that the check isn't very strong after you let NaNs through? I think the deal is that as soon as we see an NaN in any transition probability, the likelihood is going to be NaN, and we must reject the proposed state. But if we don't see an NaN, then it makes sense to check that things are not crazy.

Yes I don't think the check is very strong. Letting `NaN` through would let some bugs through. You'd probably also need to let `Inf` through. I just think checks for transition probabilities summing to sensible values should be performed by the transition probability matrix or other code that deals with computaiton of transition probabilities. Here we are simply summing likelihoods. It's not a logical place for this check.
