### ISSUE TITLE
sample script simple DEC analysis

### ISSUE THREAD

**Issue by FK1971** [revbayes/revbayes#144]
I have been running the sample script and found that the following line created a problem in creating the tree with ancestral states:

anc_tree = ancestralStateTree(tree=mcc_tree,
                              ancestral_state_trace_vector=state_trace,
                              tree_trace=tree_trace,
                              include_start_states=true,
                              file=out_str+".ase.tre",
                              burnin=n_burn,
                              site=0)

Prompts an error message stating that .. site cannot be 0. 
When I write "site=1)" instead (last line), the script works and writes the tree.

**Comment by hoehna** [comment]
Thanks for pointing out the issue. I've corrected the example (and all other occurrences).
