### ISSUE TITLE
Terminal hangs when pressing TAB in Ubuntu

### ISSUE THREAD

**Issue by bjoelle** [revbayes/revbayes#152]
The problem appeared when typing 
> source(" 

in the RB terminal then pressing TAB. The RB terminal then hanged for several minutes.

**Comment by njbooher** [comment]
I believe this was the result of tab completion looking for files recursively, which was slow in big directories.

Should be fixed.

https://github.com/revbayes/revbayes/commit/24f8ecffe7415f3820a2c0ee9c71bef442c70cc1
