### ISSUE TITLE
Issues building the latest revbayes 1.0.10 release

### ISSUE THREAD

**Issue by max1c** [revbayes/revbayes#153]
[ 71%] Building CXX object revlanguage/CMakeFiles/rb-parser.dir
/revbayes/revbayes-1.0.10/src/revlanguage/moves/scalar/Move_Slide.cpp.o
/revbayes/revbayes-1.0.10/src/core/utils/MpiUtilities.cpp: In function ‘void RevBayesCore::MpiUtilities::DebugWait(int)’:
/revbayes/revbayes-1.0.10/src/core/utils/MpiUtilities.cpp:23:20: error: ‘scanf’ was not declared in this scope
      scanf("%c", &a);
                    ^
/revbayes/revbayes-1.0.10/src/core/utils/MpiUtilities.cpp:24:39: error: ‘printf’ was not declared in this scope
      printf("%d: Starting now\n", rank);
                                       ^
/revbayes/revbayes-1.0.10/src/core/utils/MpiUtilities.cpp:28:38: error: ‘printf’ was not declared in this scope
     printf("%d: Starting now\n", rank);
                                      ^
make[2]: *** [core/CMakeFiles/rb-core.dir/home/maxprok/distapps/revbayes/revbayes-1.0.10/src/core/utils/MpiUtilities.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 71%] Building CXX object revlanguage/CMakeFiles/rb-parser.dir/home/maxprok/distapps/revbayes/revbayes-1.0.10/src/revlanguage/moves/scalar/Move_Mirror.cpp.o
make[1]: *** [core/CMakeFiles/rb-core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

Getting the same errors from the dev channel.

**Comment by hoehna** [comment]
I have now added some include directives. Could you please test if this solve the issue. I could neither replicate it on my Mac, nor on our cluster running gentoo.

**Comment by max1c** [comment]
> I have now added some include directives. Could you please test if this solve the issue. I could neither replicate it on my Mac, nor on our cluster running gentoo.

I have just successfully built revbayes from the development channel. Thanks for looking at this for me!
