### ISSUE TITLE
DPP moves fail to execute

### ISSUE THREAD

**Issue by PhyloStar** [revbayes/revbayes#154]
**Describe the bug**
Some of the DPP moves are not supported in the latest version of revbayes. I commented some of the original moves so that the script executes.

#moves[mi++] = mvDPPScaleCatVals(branch_rates, ln(2.0), 3.0)
moves[mi++] = mvDPPAllocateAuxGibbs(branch_rates, 4, 10)
#moves[mi++] = mvDPPScaleCatAllocateAux(branch_rates, ln(2.0), 4, 6.0)
moves[mi++] = mvDPPGibbsConcentration(concentration, n_cats, cp_shape, cp_rate, n_branches, 6.0)

**To Reproduce**
The original script is here: https://github.com/revbayes/revbayes_tutorial/blob/master/RB_DPPRelaxedClock_Tutorial/scripts/m_DPP_bears.Rev

**Computer info**
I am using revbayes 1.1.1 on a Ubuntu machine.

**Additional context**
Are the moves based on Suchard and Huelsenbeck's paper on site rates? I was trying to make the model work for site rates.

**Comment by bjoelle** [comment]
these moves were removed and it doesn't appear that anyone is working on them
it should be fine to run without them
