### ISSUE TITLE
Bug in dev branch (commit 55801a) 

### ISSUE THREAD

**Issue by matteo-V** [revbayes/revbayes#156]
Error when building source on dev branch. 
`Caught an exception while initializing types in the workspace
   Error:	Negative value for Natural`

**Comment by hoehna** [comment]
Which commit did you use? Is that the latest version?

**Comment by matteo-V** [comment]
I listed the commit ID in the issue. I believe that it was the version that was pushed to dev yesterday. Please let me know if I can provide any more information.

**Comment by matteo-V** [comment]
This seems to be corrected in commit (e4b8d7) for Ubuntu 16.04.6.
