### ISSUE TITLE
Continuous traits with missing data cannot start

### ISSUE THREAD

**Issue by zhangchicool** [revbayes/revbayes#158]
The MCMC cannot start when analyzing continuous traits with missing data. Two examples are attached. I guess this is also related to issue #105 and has not been fixed yet. As empirical datasets usually contain missing states, it would be great if revbayes can handle that.

[traits.zip](https://github.com/revbayes/revbayes/files/6106250/traits.zip)

**Comment by hoehna** [comment]
Hi Chi,
yes, missing data in REML is implemented now in the dev-hoehna-lab branch and is currently undergoing a pull-request (https://github.com/revbayes/revbayes/pull/146). Since this is a major pull-request, it might take a few weeks before it's available. Would you mind checking if your problem persists if you build from the dev-hoehna-lab branch? 


Sebastian

**Comment by zhangchicool** [comment]
Hi Sebastian,
Thanks for the prompt response.  I tested the attached examples using the code from branch 'dev-hoehna-lab'. Both examples ran and produced sensible results.
I wonder how the missing states are handled. Do you assume a distribution and average the possible values over MCMC or if there is an analytical solution?  also it would be nice if you could provide more implementation details about dnPhyloBrownianREML (and dnPhyloOrnsteinUhlenbeckREML) or refer to some papers/documentations. 
Best,
Chi

**Comment by zhangchicool** [comment]
My humble guess is that when a parameter (e.g. a branch length) is updated, the resulting likelihood becomes extremely small or even invalid (-nan, say), so that the move never gets accepted. 
Dataset 2 has many missing states and revbayes can not handle somehow?

**Comment by jasminelmah** [comment]
@hoehna Can I ask whether the merge request was successful? Is the ability to run dnPhyloBrownianREML with NAs possible now?

**Comment by zhangchicool** [comment]
I believe this issue is not completely fixed yet, particularly for the data attached here (https://github.com/revbayes/revbayes/files/6113242/rb-test2.zip). As noted, the MCMC has trouble to update the topology (and potentially other parameters). I am not sure if it is related to some patterns of the missing data in the matrix, e.g., would a column like (1.1 ? ? ? ?) work?
