### ISSUE TITLE
[BUG] strange category assignment by SiteMixtureAllocation when using coding="variable" on morphology data

### ISSUE THREAD

**Issue by YiyanYang0728** [revbayes/revbayes#160]
Dear Sir/Madam,

I am working on applying the RevBayes v1.1.1 (I cloned it from github at the beginning of this month) to the bear multistate morphology data provided in RevBayes tutorial. I have added the “mnSiteMixtureAllocation” monitor to figure out which category that each site belongs to.

Below is the script:
```

#######################
# Reading in the Data #
#######################

# Import the morphological character matrix #
# this file contains only the taxa for which morphological characters are available #
morpho <- readDiscreteCharacterData("data/bears_morphology.nex")

# Create some vector for the moves and monitors of this analysis
moves    = VectorMoves()
monitors = VectorMonitors()


##############
# Tree model #
##############

# Here we use a fixed tree topology of mammals on a family level sampling
# Note that the readTrees function always returns a vector of trees, 
# so we simple take the first tree
phylogeny <- readTrees("data/bears.tree")[1]

###########################################
###########################################

# Specify the number of categories we would like to use to describe the data
num_cats = 2

###########################################
# Create the Q matrix.
#
diag_rates = [ [ 0, 1],[ 100, 0]]
Q_morpho[1] := fnFreeK(diag_rates)
Q_morpho[2] := fnJC(2)

###########################################

###########################################
# We also use a discretized gamma distribution of rate categories #
# again, the shape parameter is drawn from an lognormal prior #
alpha_morpho ~ dnUniform( 0.0, 1E6 )
rates_morpho := fnDiscretizeGamma( alpha_morpho, alpha_morpho, 4 )

# Moves on the parameters to the Gamma distribution.
moves.append( mvScale(alpha_morpho, lambda=1, weight=2.0) )
###########################################


###########################################
# Tell the model what the probability of a character going into any particular category.
# This prior says that a character is equally likely to be put into any category.
mat_prior <- rep(1,num_cats)
matrix_probs ~ dnDirichlet(mat_prior)

moves.append( mvBetaSimplex(matrix_probs, weight=3.0) )
moves.append( mvDirichletSimplex(matrix_probs, weight=1.5) )
###########################################

phyMorpho ~ dnPhyloCTMC(tree=phylogeny, siteRates=rates_morpho, Q=Q_morpho, type="Standard", coding="variable", siteMatrices=matrix_probs)
phyMorpho.clamp(morpho)

########
# MCMC #
########

# initialize the model object #
mymodel = model(phylogeny)
# Create a vector of monitors #
# 1. for the full model #
monitors.append( mnModel(filename="output/bear.log", printgen=10,separator = TAB) )
# 2. and a few select parameters to be printed to the screen #
monitors.append( mnScreen(printgen=1000) )

monitors.append(mnSiteMixtureAllocation(
ctmc=phyMorpho,
filename="output/bear.siteMixture.txt",
type="Standard",
printgen=10,
separator = TAB
)
)

# Initialize the MCMC object #
mymcmc = mcmc(mymodel, monitors, moves, nruns=2, combine="mixed")

# Run the MCMC #
mymcmc.run(generations=10000, tuningInterval=200)

# check the performance of the MCMC/moves
mymcmc.operatorSummary()

# Quit RevBayes #
q()
```

---------------------

But while running a warning showed up:
**WARNING: There are 8 characters incompatible with the specified coding bias. These characters will be excluded.**

And when looked at the siteMixture_run_1.txt file, some sites were assigned with strange categories (instead of 1 or 2):
```
> cut -f120 bear.siteMixture_run_1.txt | head
site_matrix[57]
11947358874127
11947358874441
11947358874441
11947358874441
11947358874441
11947358874441
11947358874441
11947358874441
11947358874441
```

But when removing the coding="variable" from line: 
`phyMorpho ~ dnPhyloCTMC(tree=phylogeny, siteRates=rates_morpho, Q=Q_morpho, type="Standard", coding="variable", siteMatrices=matrix_probs)`
Strange categories in bear.siteMixture_run_1.txt were gone. 

Yet since the coding="variable" is necessary for morphology data according to RevBayes tutorial ("Ascertainment_Bias" section in https://revbayes.github.io/tutorials/morph_tree), so we thought this might be a bug.

I noticed that another mnSiteMixtureAllocation issue (#147) is closed and corresponding code has been updated in the latest version of RevBayes, but I still encounted with this problem.

Attached are the code, data and output zipped in a file. Thank you very much for your help.

[revbayes_test_1.zip](https://github.com/revbayes/revbayes/files/6153770/revbayes_test_1.zip)

**Comment by YiyanYang0728** [comment]
> Hi there!
> 
> The variable coding correction is for when you have data that exclude invariant characters. This means that the rest of the characters are either parsimony-informative variation or parsimony uninformative variation (such as autapomorphies) If this is giving you this error, that means that in one or more of your partitions that aren't varying. Do you perhaps have characters that are invariant, or character that have missing data that might make them appear not to vary. For example, if there are two character states at a site, but all of the taxa that have character state two have missing data?

Hi,

This is the example data I used, which is also provided in the RevBayes tutorial:
```
#NEXUS
BEGIN DATA;
	DIMENSIONS  NCHAR=62 NTAX=8;
	FORMAT DATATYPE=STANDARD GAP=- MISSING=? SYMBOLS="01";
	
	MATRIX
	Ailuropoda_melanoleuca   10111101101001000001111010111001010011000011101001011000100010
	Helarctos_malayanus      01000010011001010101011000011010011010011100000011011001001101
	Melursus_ursinus         01001010010100000101011110011001110100000101000111111111111101
	Tremarctos_ornatus       11000010110011000101111010011101011110101101001111111001101110
	Ursus_americanus         01000010010000110101011100001010000010011100000110111011001101
	Ursus_arctos             01000010010100111101011100001110000010111101010110111011001101
	Ursus_maritimus          01000010010100111001011000011010011010111000010110111011001101
	Ursus_thibetanus         01001011010001010101011100001010111010111100000110111001011110
;

END;
```
![image](https://user-images.githubusercontent.com/54937160/111510130-dc074080-8723-11eb-8011-0bef68c72ec3.png)

I see. There are indeed some sites containing only 1s. So if there is a site without any variants, the warning shows up. 

But what if I want to add the variable coding correction to the trait data containing some invariant sites? Could coding="unformative" be useful? Should I delete these invarying sites?
I think it is inevitable that many morphology data will include a small faction of invariant characters (like all 1s at a site in the above example), but it is still needed to be corrected due to their not using or ignorance of all-0 characters in the data. I am just wondering how I could consider the unseen "all-0" sites in the mophology data.

**Comment by wrightaprilm** [comment]
> But what if I want to add the variable coding correction to the trait data containing some invariant sites?

In that case you don't need the correction at all. The correction is on the total matrix, not individual characters. So if you have some characters that are invariant, you can either leave the coding off or use 'coding=all'.

**Comment by YiyanYang0728** [comment]
> In that case you don't need the correction at all. The correction is on the total matrix, not individual characters. So if you have some characters that are invariant, you can either leave the coding off or use 'coding=all'.

Thank you. But here is the problem. 

When we use coding="variable", the results are very different than coding="all".  We think that is because the program considered the "unseen" all-0 invariant sites and make the results more reasonable. 

In fact, we did 2 tests on our data (about assigning different Q matrices to each site): 1) run Revbayes with coding="variable" ;  2) run RevBayes with coding as default value or ="all". The rest of the codes as well as the input data remain exactly the same (and we make sure the results are converged by convenience R package with control$tracer=T) :

However, the matrix_prob[1] and matrix_prob[2] are very different in 2 log files:

for the first script (coding="variable"):
```
Iteration       Posterior       Likelihood      Prior   matrix_probs[1] matrix_probs[2]
0       -97841.56       -97841.56       0       0.948514        0.0514864
10      -97758.06       -97758.06       0       0.446618        0.553382
20      -97754.12       -97754.12       0       0.132334        0.867666
30      -97749.44       -97749.44       0       0.208958        0.791042
40      -97754.07       -97754.07       0       0.358151        0.641849
50      -97750.42       -97750.42       0       0.200699        0.799301
60      -97749.55       -97749.55       0       0.24963 0.75037
70      -97749.46       -97749.46       0       0.213881        0.786119
80      -97749.84       -97749.84       0       0.184621        0.815379
.....
99950   -97750.81       -97750.81       0       0.305383        0.694617
99960   -97751.88       -97751.88       0       0.221776        0.778224
99970   -97751.61       -97751.61       0       0.212832        0.787168
99980   -97749.36       -97749.36       0       0.219081        0.780919
```
for the second script (coding as default or ="all"):
```
Iteration       Posterior       Likelihood      Prior   matrix_probs[1] matrix_probs[2]
0       -127504.6       -127504.6       0       0.999466        0.000533745
10      -127500.4       -127500.4       0       0.999311        0.000688676
20      -127502.4       -127502.4       0       0.997947        0.00205259
30      -127500.3       -127500.3       0       0.999501        0.000499157
40      -127501.9       -127501.9       0       0.997088        0.00291231
50      -127504.2       -127504.2       0       0.994821        0.00517915
60      -127500.4       -127500.4       0       0.999275        0.000725002
70      -127500.1       -127500.1       0       0.999585        0.000415242
80      -127503.5       -127503.5       0       0.996531        0.00346893
...
99960   -127501.3       -127501.3       0       0.999992        7.64738e-06
99970   -127500.3       -127500.3       0       0.999615        0.000384897
99980   -127500.7       -127500.7       0       0.999383        0.000617327
99990   -127500.5       -127500.5       0       0.999704        0.000295731
100000  -127500.2       -127500.2       0       0.999469        0.00053074
```
We could see in the first run (coding="variable"), mat_probs converged to a mean of [ 0.2287369, 0.7712631], while in the second run (default coding="all") to [0.998650781, 0.001349216]. 

Will coding="variable" have such big impact on matrix_probs? We'd really appreciate your help.

**Comment by wrightaprilm** [comment]
I think something else is going on here. Using your same data and code, I get likelihoods like those seen in the tutorial, on the order of -300. In yours, a the value of the prior is not being calculated. Were these two logs generated using the code in the attached zip file?

**Comment by YiyanYang0728** [comment]
> I think something else is going on here. Using your same data and code, I get likelihoods like those seen in the tutorial, on the order of -300. In yours, a the value of the prior is not being calculated. Were these two logs generated using the code in the attached zip file?

No I will give you the code and data we used. Above are the specific questions we encounted in the real data. They are attached below.
[RevBayes_test.zip](https://github.com/revbayes/revbayes/files/6159869/RevBayes_test.zip)

By the way, I saw the source code (https://github.com/revbayes/revbayes/blob/acd1640a7a0e832bbae36ee9ba0c9310d512c77e/src/core/distributions/phylogenetics/substitution/PhyloCTMCSiteHomogeneousBinary.h) that "coding" could be given a value "NOSINGLETONABSENCE", I think that might be what we want. But when we tried this value, an error indicated that coding bias doesn't have this option.

**Comment by wrightaprilm** [comment]
That makes more sense. In this case, I do think it's reasonable that choosing `coding=variable` would make such a large difference. When you choose that option, in this case, you exclude a little more than a fifth of your data that is invariant. The likelihood calculated by RevBayes using this reduced dataset is about 25% lower than with the full data. In the case of the morphology characters, when you use `coding=variable`, 8/62 characters are excluded, for a reduction in the calculated likelihood of about ten percent.

**Comment by YiyanYang0728** [comment]
> That makes more sense. In this case, I do think it's reasonable that choosing `coding=variable` would make such a large difference. When you choose that option, in this case, you exclude a little more than a fifth of your data that is invariant. The likelihood calculated by RevBayes using this reduced dataset is about 25% lower than with the full data. In the case of the morphology characters, when you use `coding=variable`, 8/62 characters are excluded, for a reduction in the calculated likelihood of about ten percent.

I see. Thank you for your explanation. Would you recommend us to delet those invariant sites in our data and still use coding="variable" in the script? 

By the way, I saw the source code (https://github.com/revbayes/revbayes/blob/acd1640a7a0e832bbae36ee9ba0c9310d512c77e/src/core/distributions/phylogenetics/substitution/PhyloCTMCSiteHomogeneousBinary.h) that "coding" could be given a value "NOSINGLETONABSENCE", would that be helpful? But when we tried this value, an error indicated that coding bias doesn't have this option for standard-type data. 

And I changed the data type from "standard" to "binary" and it looks like it worked but with a warning "WARNING: There are 1042 characters incompatible with the specified coding bias. These characters will be excluded.".

**Comment by wrightaprilm** [comment]
> I see. Thank you for your explanation. Would you recommend us to delet those invariant sites in our data and still use coding="variable" in the script?

I don't see any reason to prefer this. 

> hat "coding" could be given a value "NOSINGLETONABSENCE", would that be helpful? But when we tried this value, an error indicated that coding bias doesn't have this option for standard-type data.

This I'm not sure about. This was implemented by @willpett for gene content work, I believe. Perhaps he has more insight on this.

> And I changed the data type from "standard" to "binary" and it looks like it worked but with a warning "WARNING: There are 1042 characters incompatible with the specified coding bias. These characters will be excluded.".

I was not able to reproduce this behavior. How did you do this?

**Comment by YiyanYang0728** [comment]
> > I see. Thank you for your explanation. Would you recommend us to delet those invariant sites in our data and still use coding="variable" in the script?
> 
> I don't see any reason to prefer this.
Thank you. I will keep trying.
> 
> > hat "coding" could be given a value "NOSINGLETONABSENCE", would that be helpful? But when we tried this value, an error indicated that coding bias doesn't have this option for standard-type data.
> 
> This I'm not sure about. This was implemented by @willpett for gene content work, I believe. Perhaps he has more insight on this.
Thanks for prodiving other helps.
> 
> > And I changed the data type from "standard" to "binary" and it looks like it worked but with a warning "WARNING: There are 1042 characters incompatible with the specified coding bias. These characters will be excluded.".
> 
> I was not able to reproduce this behavior. How did you do this?
I simply modified the code on line 73 in scripts/Ecoli_test_wo_rates_var.rev to:
`phyMorpho ~ dnPhyloCTMC(tree=phylogeny, Q=Q_morpho, type="Binary", coding="nosingletonabsence", siteMatrices=matrix_probs)`

**Comment by YiyanYang0728** [comment]
Thanks for patiently answering my questions. I think I will just use coding="all". But I am looking forward to a tutorial on how to use coding="noabsencesites", since I get to know this option in MrBayes' manual.
