### ISSUE TITLE
[BUG] collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by pyspider** [revbayes/revbayes#178]
**Describe the bug**
I have been tried to compile MPI version on hpc. But fails at 100%.
Any help much appreciated!

**To Reproduce**

>  ./build.sh -mpi true
> Building rb
> CC=  CXX=
> Generating version numbers in GitVersion.cpp
> fatal: Not a git repository (or any parent up to mount point /gpfs)
> Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> fatal: Not a git repository (or any parent up to mount point /gpfs)
> Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> Running './regenerate.sh /gpfs/home/li/usr/opt/revbayes-1.1.1/projects/cmake/build
> Making build directory '/gpfs/home/li/usr/opt/revbayes-1.1.1/projects/cmake/build'
> Generating src/generated_include_dirs.cmake
> Generating src/libs/CMakeLists.txt
> Generating src/core/CMakeLists.txt
> Generating src/revlanguage/CMakeLists.txt
> Generating src/help2yml/CMakeLists.txt
> Generating src/cmd/CMakeLists.txt
> 
> 
> Running 'cmake ../../../src -DRB_EXEC_NAME=rb ' in /gpfs/home/li/usr/opt/revbayes-1.1.1/projects/cmake/build
> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 4.8.5
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> Boost location hints:
>   BOOST_ROOT not set
> Searching for BOOST:
> CMake Warning at /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
>   Imported targets not available for Boost version 106900
> Call Stack (most recent call first):
>   /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
>   /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
>   CMakeLists.txt:94 (find_package)
> 
> 
> CMake Warning at /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
>   Imported targets not available for Boost version 106900
> Call Stack (most recent call first):
>   /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
>   /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
>   CMakeLists.txt:94 (find_package)
> 
> 
> CMake Warning at /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
>   Imported targets not available for Boost version 106900
> Call Stack (most recent call first):
>   /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
>   /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
>   CMakeLists.txt:94 (find_package)
> 
> 
> CMake Warning at /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
>   Imported targets not available for Boost version 106900
> Call Stack (most recent call first):
>   /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
>   /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
>   CMakeLists.txt:94 (find_package)
> 
> 
> CMake Warning at /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
>   Imported targets not available for Boost version 106900
> Call Stack (most recent call first):
>   /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
>   /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
>   CMakeLists.txt:94 (find_package)
> 
> 
> CMake Warning at /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
>   Imported targets not available for Boost version 106900
> Call Stack (most recent call first):
>   /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
>   /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
>   CMakeLists.txt:94 (find_package)
> 
> 
> CMake Warning at /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
>   Imported targets not available for Boost version 106900
> Call Stack (most recent call first):
>   /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
>   /gpfs/home/li/usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
>   CMakeLists.txt:94 (find_package)
> 
> 
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE
> -- Boost version: 1.69.0
> -- Found the following Boost libraries:
> --   regex
> --   program_options
> --   thread
> --   system
> --   filesystem
> --   date_time
> --   serialization
> Boost configuration results:
>   Boost_INCLUDE_DIRS: /usr/local/include
>   Boost_LIBRARY_DIRS: /usr/local/lib
>   Boost_LIBRARIES: /usr/local/lib/libboost_regex.so;/usr/local/lib/libboost_program_options.so;/usr/local/lib/libboost_thread.so;/usr/local/lib/libboost_system.so;/usr/local/lib/libboost_filesystem.so;/usr/local/lib/libboost_date_time.so;/usr/local/lib/libboost_serialization.so
> Compile information:
>   CMAKE_BUILD_TYPE =
>   CMAKE_CXX_FLAGS =  -std=c++11 -msse -msse2 -msse3 -O3 -DNDEBUG
>   CMAKE_C_FLAGS =  -msse -msse2 -msse3 -O3 -DNDEBUG
> Building rb
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /gpfs/home/li/usr/opt/revbayes-1.1.1/projects/cmake/build
> 
> Running 'make -j 4' in /gpfs/home/li/usr/opt/revbayes-1.1.1/projects/cmake/build

**Expected behavior**

**Screenshots**
> [100%] Linking CXX executable ../rb-mpi
> CMakeFiles/rb-mpi.dir/revlanguage/main.cpp.o: In function `parse_cmd_line(int, char**)':
> main.cpp:(.text+0x24c): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
> CMakeFiles/rb-mpi.dir/revlanguage/main.cpp.o: In function `boost::program_options::typed_value<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, char>::name() const':
> main.cpp:(.text._ZNK5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcE4nameEv[_ZNK5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcE4nameEv]+0x27): undefined reference to `boost::program_options::arg[abi:cxx11]'
> main.cpp:(.text._ZNK5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcE4nameEv[_ZNK5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcE4nameEv]+0x2d): undefined reference to `boost::program_options::arg[abi:cxx11]'
> CMakeFiles/rb-mpi.dir/revlanguage/main.cpp.o: In function `boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*)':
> main.cpp:(.text._ZN5boost15program_options25basic_command_line_parserIcEC2EiPKPKc[_ZN5boost15program_options25basic_command_line_parserIcEC5EiPKPKc]+0x1c8): undefined reference to `boost::program_options::to_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> main.cpp:(.text._ZN5boost15program_options25basic_command_line_parserIcEC2EiPKPKc[_ZN5boost15program_options25basic_command_line_parserIcEC5EiPKPKc]+0x247): undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
> CMakeFiles/rb-mpi.dir/revlanguage/main.cpp.o: In function `main':
> main.cpp:(.text.startup+0x1bc): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> main.cpp:(.text.startup+0x24d): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> main.cpp:(.text.startup+0x4c0): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> main.cpp:(.text.startup+0x62b): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> main.cpp:(.text.startup+0x893): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> CMakeFiles/rb-mpi.dir/revlanguage/main.cpp.o: In function `void boost::program_options::validate<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, int)':
> main.cpp:(.text._ZN5boost15program_options8validateINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEEvRNS_3anyERKSt6vectorINS3_IT0_S4_ISB_ESaISB_EEESaISE_EEPSA_IT_SaISJ_EEi[_ZN5boost15program_options8validateINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEEvRNS_3anyERKSt6vectorINS3_IT0_S4_ISB_ESaISB_EEESaISE_EEPSA_IT_SaISJ_EEi]+0x92): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
> main.cpp:(.text._ZN5boost15program_options8validateINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEEvRNS_3anyERKSt6vectorINS3_IT0_S4_ISB_ESaISB_EEESaISE_EEPSA_IT_SaISJ_EEi[_ZN5boost15program_options8validateINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEEvRNS_3anyERKSt6vectorINS3_IT0_S4_ISB_ESaISB_EEESaISE_EEPSA_IT_SaISJ_EEi]+0x483): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> CMakeFiles/rb-mpi.dir/revlanguage/main.cpp.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> CMakeFiles/rb-mpi.dir/revlanguage/main.cpp.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> CMakeFiles/rb-mpi.dir/revlanguage/main.cpp.o:(.rodata._ZTCN5boost10wrapexceptINS_15program_options20invalid_option_valueEEE0_NS_16exception_detail10clone_implINS4_19error_info_injectorIS2_EEEE[_ZTVN5boost10wrapexceptINS_15program_options20invalid_option_valueEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> CMakeFiles/rb-mpi.dir/revlanguage/main.cpp.o:(.rodata._ZTVN5boost10wrapexceptINS_15program_options20invalid_option_valueEEE[_ZTVN5boost10wrapexceptINS_15program_options20invalid_option_valueEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> CMakeFiles/rb-mpi.dir/revlanguage/main.cpp.o:(.rodata._ZTVN5boost15program_options16validation_errorE[_ZTVN5boost15program_options16validation_errorE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> CMakeFiles/rb-mpi.dir/revlanguage/main.cpp.o:(.rodata._ZTVN5boost15program_options20invalid_option_valueE[_ZTVN5boost15program_options20invalid_option_valueE]+0x30): more undefined references to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const' follow
> CMakeFiles/rb-mpi.dir/revlanguage/main.cpp.o:(.rodata._ZTVN5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcEE[_ZTVN5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
> collect2: error: ld returned 1 exit status
> make[2]: *** [../rb-mpi] Error 1
> make[1]: *** [CMakeFiles/rb-mpi.dir/all] Error 2
> make: *** [all] Error 2

**Computer info**
Red Hat Enterprise Linux Server release 7.5 (Maipo)
revbayes-1.1.1 & revbayes-development

**Additional context**

**Comment by bredelings** [comment]
It looks like some symbols referenced by the compiled code were not found in the BOOST libraries.  I suspect that this problem no longer occurs -- can you check?

If it does occur, you could follow the instructions for compiling BOOST here:

     https://revbayes.github.io/compile-linux

**Comment by bredelings** [comment]
This is probably fixed.
