### ISSUE TITLE
[Help Wanted] Ask for help about how to assign branch-specific Q matrices

### ISSUE THREAD

**Issue by YiyanYang0728** [revbayes/revbayes#180]
**Describe the desired behavior.**
I want to assign different Q matrices for different branches. I noticed that for function dnPhyloCTMC, Q parameter could accept branch-specific matrices.

**What is going wrong?**
I read through the tutorial but found no instructions about this.

**Anything else you've tried?**
I found that there is a way to assign branch-specific rates in OU or BM model. I was thinking if it is similar to build branch-specific Q matrices.

**Screenshots**
![image](https://user-images.githubusercontent.com/54937160/127390602-ea23db97-cd70-43d6-a862-aa2c0d84b09c.png)

I am wondering if there is any tutorials, documents or code for how to use or build branch-specific Q matrcies. I'd really appreciate your help.

Thanks,
Yiyan

**Comment by bredelings** [comment]
From reading the code, it looks the Q parameter can be a vector of RateGenerators.  I general parameters can sometimes accept multiple different argument types, but only the first one is shown.  For example, `siteMatrices` can be either `Simplex` or `Bool`, but only `Simplex` is shown in the help.

If you leave `siteMatrices` unset, or set it to false, then the vector of Q matrices is interpreted as a vector for each branch.  In that case you have to specify `rootFrequencies`, which makes sense.

So presumably the first Q matrix corresponds to branch 0, the second Q matrix corresponds to branch 1, etc.  I guess you would have to figure out which branch is number 0, number 1, etc.

**Comment by bredelings** [comment]
I haven't found a tutorial or test that does this, but that doesn't mean there isn't one.
