### ISSUE TITLE
Understanding rooting of time trees [Help Wanted]

### ISSUE THREAD

**Issue by jasminelmah** [revbayes/revbayes#199]
Hello!

I am drawing ultrametric trees from dnBirthDeath and, as time trees, they come out rooted. However, I have not specified an outgroup (I don't have enough prior information for this) so I was wondering if you could clarify how RevBayes selects the root of a time tree? Is it random? If it is based on some kind of information inherent to the data, what kind of information is that and how does RevBayes arrive at a root?

Thanks for helping me understand this!

**Comment by davidcerny** [comment]
Just in case this might be useful to other users: yes, the birth-death process induces a prior distribution on rooted trees, and when we use it to estimate time trees (or "clock trees", as they are also called), these are intrinsically rooted. The position of the root is not random; it is estimated from the data. Character data can only inform the position of the root through the information they contain about branch lengths (= amounts of change). While any given branch length can be produced by infinitely many combinations of rate and time, not all of these are equally probable under our specified clock prior and tree prior (such as `dnBirthDeath`), meaning that some root positions will end up being favored over others. This was explicitly noted by Drummond et al. ([2006, _PLoS Biol._ 4(5): e88](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.0040088)) in their classic introduction to relaxed-clock models:

> If the rate and time along each branch can only be estimated as their product, then the position of the root of the tree cannot be estimated without additional assumptions such as an outgroup or a non-reversible substitution process.

> One of the byproducts of estimating a phylogeny using a relaxed clock is an estimate of the position of the root of the tree, even in the absence of a non-reversible model of substitution or a known outgroup.

Intuitively, we can make sense of this by a thought experiment: what would happen if we were to reroot a time tree, as we often do with non-clock trees? A rerooted tree of extant species would no longer be ultrametric, so some taxa would spuriously appear "older" than others despite the fact that they are all perfectly contemporaneous. This is a nonsensical result, demonstrating that the position of the root is an intrinsic part of the tree estimate we have obtained.
