### ISSUE TITLE
[BUG] clades within clade objects

### ISSUE THREAD

**Issue by JFFleming** [revbayes/revbayes#215]
Where clade objects are used to make furthers clade objects, their behaviour doesn't seem to match up clearly with the behaviour as described in the documentation. This is particularly relevant to the optional and negative flags.
https://revbayes.github.io/documentation/clade.html

Regarding Optional Clades:
In the scenario depicted in the documentation

```
clade_67 = clade( taxa[6], taxa[7] )
clade_68 = clade( taxa[6], taxa[8] )
clade_67_68 = clade( clade_67, clade_68, optional_match=true )
```

The conflicting clade constraints (8,(6,7) and (7,(6,8) register as TRUE for the containsClade checker, but so does the third option of (6,(7,8). This is because all three taxa are contained within the clade object clade_67_68 , which removes the separation passed by the constituent clade markers. This theory is supported by calling clade_67_68 in revbayes, which displays as

clade_67_68
{taxa[6],taxa[7],taxa[8]}

In the case of non-conflicting monophyletic constraints (such as clade 78, clade 678), the common practice in RevBayes would be as follows

```
clade_78 = clade( taxa[7], taxa[8] )
clade_678 = v(taxa[6],clade_78)
```

but this removes the ability to use the optional flag to evaluate two conflicting sister topologies, as implied in the documentation to be the purpose of the Optional flag.

**To Reproduce**

SimpleTree.tre is:
(Taxa1,(Taxa2,(Taxa3,(Taxa4,Taxa5))));

```
Tree1<-readTrees("SimpleTree.tre")
Test34=clade("Taxa3","Taxa4")
Tree1[1].containsClade(Test34)
Test35=clade("Taxa3","Taxa5")
Tree1[1].containsClade(Test35)
Test34_35=clade(Test34, Test35)
OptionTest34_35=clade(Test34, Test35, optional_match=true)
Tree1[1].containsClade(OptionTest34_35)
```
containsClade 34_45 is additionally returned as TRUE with the optional_match flag set to false, and with the negative flag set to true in all combinations.

**Expected behavior**
The clade documentation page seems to imply that Test34_35, OptionTest34_35 and, more broadly, clade objects made up of other clade objects might behave more like

`v(Test34, Test35)
`

Where the information passed from the constituent clade objects informs its structure, but with ability to set flags like Optional and Negative.

**Comment by bredelings** [comment]
Comments on clade versus constraints in #288 may be relevant.

**Comment by JFFleming** [comment]
Oh thanks! Definitely I think so - and much better than the solution I have been trying t work out with an altered dnUniformTopology. This is something I'm really interested in, so I'll review these straight away

**Comment by bredelings** [comment]
Note that the idea of separating clades and constraints is still just an idea...
