### ISSUE TITLE
[BUG] computePairwiseRFDistances returns vector of wrong size

### ISSUE THREAD

**Issue by davidcerny** [revbayes/revbayes#229]
For a trace of _n_ trees, the `computePairwiseRFDistances()` method is expected to return a vector of _n_*(_n_ - 1)/2 unique distances. However, there are cases where the resulting vector is of the wrong size. A minimum reproducible example: for the two trees included in the file below, the following produces a vector containing two RF distances rather than just one.

```
a = readTrees("test.txt")
b = treeTrace(a, burnin=0.0)
b.computePairwiseRFDistances(credibleTreeSetSize=1.0, verbose=TRUE)
```

I get this problem using development builds going at least as far back as 8ec2e0c (May 2021).
[test.txt](https://github.com/revbayes/revbayes/files/8454271/test.txt)

**Comment by bredelings** [comment]
@davidcerny I think this is fixed on the development branch and in the latest preview release.  Can you check?

**Comment by davidcerny** [comment]
Indeed – thanks a lot for fixing this in #294; closing the issue now!
