### ISSUE TITLE
[BUG] Unable to read trees with sampled ancestors in development

### ISSUE THREAD

**Issue by brpetrucci** [revbayes/revbayes#240]
**Describe the bug**
Since pulling from development on May 2nd, my scripts have errored when reading trees with sampled ancestors. The specific error is `Problem while working with tree: Node had bad index. Two nodes had same index of '0'.` This same error is not present when compiling and running the master branch. Furthermore, reading an ultrametric tree or one with extant and fossil tips (but no ancestors) does not lead to error. 

**To Reproduce**
From my tests any tree with sampled ancestors will error, but an example can be downloaded from [here](https://github.com/brpetrucci/ssefbd_evol22/blob/main/eeob565/simulation/replicates/1_base/trees/fbd/tree_fbd_1.nex), while the equivalent ultrametric tree can be found [here](https://github.com/brpetrucci/ssefbd_evol22/blob/main/eeob565/simulation/replicates/1_base/trees/ultrametric/tree_ultra_1.nex), and the tree with fossil and extant tips, but no SAs, [here](https://github.com/brpetrucci/ssefbd_evol22/blob/main/eeob565/simulation/replicates/1_base/trees/tree_1.nex). If `tree.nex` is the name of the file in question, to reproduce one need simply run `readTrees(file = "tree.nex")[1]`

**Computer info**
MacOS Big Sur 11.6, RevBayes development commit ebf2aa7 (Apr 29 2022)

**Comment by wrightaprilm** [comment]
I am also having this issue on Mac Catalina 10.15.7 and Linux Ubuntu 22.04 LTS.

**Comment by brpetrucci** [comment]
Tried a couple commits up to 8a31d1e (Mar 11) and problem persists.

**Comment by brpetrucci** [comment]
Closed by mistake. Problem still persists in current (Aug 23) version of development

**Comment by bredelings** [comment]
I'll try and take a look...   have you tried compiling a debug version and looking at it in `gdb` or the xcode debugger?

**Comment by bredelings** [comment]
@brpetrucci Can you try to make  small tree that reproduces the problem?  I'm curious what the smallest tree that yield this type of error is.  This would serve as a "reduced testcase" that makes it easier to debug.

**Comment by bredelings** [comment]
@brpetrucci I think I've fixed this on #263 - can you try that out?

**Comment by brpetrucci** [comment]
Seem like it's working! Thank you Ben.
