### ISSUE TITLE
[BUG] Segmentation fault when running PPS on FBD model

### ISSUE THREAD

**Issue by oschwery** [revbayes/revbayes#241]
**Describe the bug**
We've run an FBD model and I am now trying to run `posteriorPredictiveSimulation()` on it. I can set it all up, but when I try to `.run` it, CPU use briefly spikes, and revbayes crashes with the message:
`Segmentation fault (core dumped)`

**To Reproduce**
A reproducible example can be found [here](https://github.com/oschwery/FBD_PPS), in the directory `0/`. 
The run I attempted should be reproduced by `source("run_PPS.Rev")`.

**Expected behavior**
I would expect the posterior predictive simulations to start and the corresponding files to start appearing in the directory `PPS_output/`.

**Screenshots**
NA

**Computer info**
OS: Pop!_OS 21.10 64-bit

RevBayes version (1.1.1)
Build from dev-hoehna-lab (rapture-1128-g12592c) on Mon Mar  7 11:05:31 AM CST 2022

**Additional context**
We also tried running it with rb-mpi, to alleviate the memory pressure, but that did not help, as one of the threads will always spike and crash the whole run.

**Comment by oschwery** [comment]
Apparently it works as expected with the most recent tagged release (Rapture-588-gae00cc), just not the dev version we used... (However, the output of that doesn't seem quite right yet)

**Comment by bredelings** [comment]
Also, @willpett may have a comment on this, since he is working on the FBD on development.

**Comment by wrightaprilm** [comment]
I don't think it's a direct FBD problem, as the same FBD script works fine with MCMC and steppingstone. I think it's specifically the PPS. I'm recompiling for use with gdb right now.

**Comment by wrightaprilm** [comment]
I'm wrong! It's not PPS specific. The segmentation fault localizes to AbstractHomologousDiscreteCharacterData::applyMissingSitesMask. Removing this allows us to run the PPS pipeline fine with FBD. When I run the PPS tutorial files, this function doesn't seem to cause problems. But there are no data in that one demarcated with a '?'. So I made a test case with a morphology matrix that has plenty of missing data and used the PPS tutorial files. Completely fine. 

So this is quite confusing: this function `applyMissingSitesMask` isn't FBD-specific.

**Comment by bredelings** [comment]
I ran the example for 5 minutes without a crash using current development.  It got to about 12.5% complete.  When this crashed, how long did you have to wait in order to see the crash?

**Comment by wrightaprilm** [comment]
I'm running into this issue again with a different dataset. I run the data-based PPS, and that's largely OK. This time, the issue seems to be that the file parser isn't allocating memory quite right on the read-in from the data-based PPS output to initialize the inference-based PPS. I've taken a look in Serializeable.cpp, but it looks OK to me (admittedly not the strongest C++ person).

>  in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
> #1  0x0000555556b0a859 in RevBayesCore::RbFileManager::RbFileManager (this=0x7fffffff9360, pn=<error reading variable: Cannot access memory at address 0x8>, 
>     fn="phyMorpho[1].nex") at /home/labaccount/software/revbayes-1.2.0/src/core/utils/RbFileManager.cpp:104
> #2  0x00005555562c6904 in RevBayesCore::HomologousDiscreteCharacterData<RevBayesCore::StandardState>::initFromFile (this=0x555559cf73b0, 
>     dir=<error reading variable: Cannot access memory at address 0x8>, fn="phyMorpho[1]")
>     at /home/labaccount/software/revbayes-1.2.0/src/core/datatypes/phylogenetics/characterdata/HomologousDiscreteCharacterData.h:1485
> #3  0x00005555563a353d in RevBayesCore::Serializer<RevBayesCore::AbstractHomologousDiscreteCharacterData, 1>::ressurectFromFile (obj=0x555559cf73b0, 
>     dir=<error reading variable: Cannot access memory at address 0x8>, fn="phyMorpho[1]")
>     at /home/labaccount/software/revbayes-1.2.0/src/core/datatypes/Serializer.h:101
> #4  0x00005555563a0d8c in RevBayesCore::StochasticNode<RevBayesCore::AbstractHomologousDiscreteCharacterData>::setValueFromFile (this=0x55557e2d5c10, 
>     dir=<error reading variable: Cannot access memory at address 0x8>) at /home/labaccount/software/revbayes-1.2.0/src/core/dag/StochasticNode.h:774
> #5  0x0000555556b13c91 in RevBayesCore::PosteriorPredictiveAnalysis::runAll (this=0x555568191380, gen=400000)

I'm using [this](https://drive.google.com/file/d/1ZsxSYVayxOsxsCUkDiKPBZmuJHwI5JlP/view?usp=drive_link) script with [these data](https://drive.google.com/drive/folders/1PmrPwnuAn89C0_pu-_DKRaWFn4SGWxE6?usp=drive_link). Sample data-based PPS output is [here](https://drive.google.com/drive/folders/1G0P9S8T_QkaAzNAMEReBkyAOb-M1buEx?usp=drive_link).

**Comment by wrightaprilm** [comment]
Nevermind, figured out the issue. This is related to mixed up paths.
