### ISSUE TITLE
[BUG] maximum number of monophyletic constraints is 15

### ISSUE THREAD

**Issue by anoukwillemsen** [revbayes/revbayes#250]
There appears to me a maximum to the number of monophyletic constraints you can give. This maximum number appears to be 15, when any additional constraints are included I get the following error: "Segmentation fault (core dumped)"

This error occurred when I tried to construct a timetree with constraints on the calibration nodes. If I limit the number to 15 constraints, does not matter which constraints, the error does not occur and I am able to construct my timetree

Can this error please be fixed so I am able to include more than 15 monophyletic constraints?

I am working on Linux Ubuntu 20.04.4 LTS with RevBayes v.1.1.1

**Comment by bredelings** [comment]
Hi Anouk,

Can you please provide an example script and data set that produces this problem?  If you can do that, I will take at look.

**Comment by bredelings** [comment]
Hi @anoukwillemsen, #288 might fix this.  Let me know if you want more info.

**Comment by bredelings** [comment]
Looks like #299 actually does fix this.

**Comment by bredelings** [comment]
You can test this out with the preview release https://github.com/revbayes/revbayes/releases/tag/v1.2.1-preview8

The executables will should available in about an hour.

**Comment by willgearty** [comment]
I'm currently using the Windows version of RevBayes (v1.2.1, build from 04666d), and this does not appear to be fixed. My analysis works just fine when I have 15 constraints, but when I add a single additional constraint it no longer progresses.
