### ISSUE TITLE
[BUG] Concatenating string variable with "(" fails

### ISSUE THREAD

**Issue by fkmendes** [revbayes/revbayes#292]
The following lines of code cause a Syntax error:

```
> s = ""
> s = s + "("
> s
     Syntax error while reading character '' at position 0 in command:
     s
>
```

**Comment by bredelings** [comment]
So, interestingly, this DOES work if you are not in interactive mode :-P  So, you can get this to work by putting all your commands into `file.Rev` and doing `rb file.Rev`.

When you are in interactive mode RevBayes does weird magic whenever you type a `(`.  For example:
```
> ( 1 + 
+ 2)
    3
>
```
I think its counting how many left-parens you type, and doesn't actually issue the command until you have enough right parens.

Using the debugger I can tell that when you write `s = "("`, the assignment statement is never constructed, even though the prompt for the next line is show.

I'm guessing that the code for handling `(` doesn't handle strings.

This has something to do with the linenoise and linedit libraries, but I haven't yet figured it out yet.
