### ISSUE TITLE
Use RevBayes with Rstudio

### ISSUE THREAD

**Issue by lfp-a** [revbayes/revbayes#311]
**Describe the desired behavior.**
Use RevBayes with Rstudio

**What is going wrong?**
The rb command cannot be executed in rstudio; I changed.renviron in the installation instructions but it still doesn't work

**Anything else you've tried?**
Have you tried any alternative ways to accomplish your task? If so, what?

**Screenshots**
If applicable, feel free to provide screenshots to help explain your problem.
This is the message from Rstuio
![image](https://user-images.githubusercontent.com/77486663/205844732-df1bbc16-9843-4622-aa69-521c6bd9f4c5.png)
This is the location information for revbayes-v1.2.1
![image](https://user-images.githubusercontent.com/77486663/205846321-85282a9a-9102-4170-b169-b6cd3a7f1c7b.png)

**Computer info**
R version 4.2.2 ;  revbayes-v1.2.1
Which OS are you using? Which version of RevBayes? This should be the first line you see when you start RevBayes.

**Additional context**

**Comment by wrightaprilm** [comment]
Hello,

Are you using RevBayes via the [Revticulate](https://github.com/revbayes/Revticulate) R package, or just through RStudio? I don't think this will work if you're just trying to execute RevBayes in RStudio. The Revticulate R package is meant to make this possible.

**Comment by bredelings** [comment]
I initially thought that this bug report was a mistake.  But I see that there is documentation about setting up RevBayes with RStudio here:    https://revbayes.github.io/gui-setup

Do you know if that documentation is up-to-date?

**Comment by wrightaprilm** [comment]
I need to update it; it's on my TODO list for ... soon. For now, I would use the [Revticulate](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13852) interface. Package documentation is [here](https://github.com/revbayes/Revticulate).

**Comment by wrightaprilm** [comment]
I went ahead and updated the install instructions on the website: https://revbayes.github.io/gui-setup

If these don't work for you, let me know.

**Comment by bredelings** [comment]
Hi @lfp-a,

You are trying to run revbayes (rb) directly in R Studio.  That isn't currently supported.

You install the revticulate R package, you can use it to run revbayes code from R.  But it doesn't enable RevStudio to run R code directly.

If you want to request the ability to run RevBayes code directly from R Studio, can you please open a new issue?

-BenRI
