### ISSUE TITLE
Unable to run rb commands (Mac)

### ISSUE THREAD

**Issue by nhcooper123** [revbayes/revbayes#330]
Weird issue, and apologies if this is my fault/my computer but April suggested I raise this. 

Installed revbayes, first the pre-compiled version and then I compiled it myself too. When I run any command, even just `rb`, in Terminal or in RStudio I get this error message:

`libc++abi: terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::status: File name too long [system:63]: ""&"&&&"&&&&&&&"&&&&&&&&&&&&&&&"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"modules&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"&&&&&&&&&&&&&&&"&&&&&&&"&&&"&"""
Abort trap: 6`

MacOS 11.4 (Big Sur)
Mac Pro (late 2013)

Interestingly it was working ok initially with the pre-compiled version, then I restarted RStudio and this started to appear!

**Comment by wrightaprilm** [comment]
A couple clarifying questions for when I sit down with this:

+ Which version of rb?
+ When you say RStudio, do you mean with Revticulate or via the built-in terminal in RStudio?

**Comment by nhcooper123** [comment]
Sorry those deets would have helped!

- version 1.2.1 (from here: https://revbayes.github.io/download)

- with revticulate, and with the in built terminal (and with the standard Mac terminal outside RStudio)

**Comment by wrightaprilm** [comment]
Great, thanks!

**Comment by bredelings** [comment]
I think this is the result of a corrupted RevBayes config file. I have seen
this before somewhere. If you delete the file (whose name I am forgetting
right now) that should fix the problem.

Longer term, the question is how to prevent this from happening again...

**Comment by hoehna** [comment]
Yes, the problem is a corrupted ini file. The file is in your home
directory and is called "~/.RevBayes.ini"

**Comment by nhcooper123** [comment]
Ah perfect thanks, deleting that fixed the issue!
