### ISSUE TITLE
[BUG] Columns without any data not handled correctly in any +I model

### ISSUE THREAD

**Issue by hoehna** [revbayes/revbayes#336]
**Describe the bug**
If we have a column in the sequence alignment were all characters for this site are missing or gaps (treated as the same) and we assume any substitution model with the +I model option, then RevBayes has a segmentation issue. The column is internally recognized as being invariant, and in the +I model we multiply the probability of the site being invariant with the base frequency of the observed invariant site. Since for a gap-only column we don't know the base frequency index, the index is set to -1 which retrieves arbitrary memory for the frequency. This leads to unreproducible behaviour and invalid MCMC as the likelihood can change without the parameters changing.

**To Reproduce**
See the example scripts. Since the seed is set, the MCMC should be identical if you rerun it. It doesn't. You can also see the issue when you enable the DEBUG_MCMC preprocessor macro.

[invar_sites_issue.zip](https://github.com/revbayes/revbayes/files/10919724/invar_sites_issue.zip)

**Expected behavior**
Not sure how to handle gap-only columns. Probably should be removed from the alignment?

**Comment by bjoelle** [comment]
@hoehna I would expect the behaviour of the +I models to match with the other models - do they also remove columns only composed of gaps ?

**Comment by bjoelle** [comment]
yes, problem appears to be fixed now (at least the test script gives consistent results on repeated runs) so I will close this
