### ISSUE TITLE
[BUG] consensusTree() does not return any supported clades

### ISSUE THREAD

**Issue by frithureiks** [revbayes/revbayes#361]
I noticed that the function consensusTree() does not return any supported clades. I attached a toy example posterior tree file with five taxa. When I run consensusTree() on the file, it does not return any supported clades while both mccTree() and mapTree() find groupings with posterior support > .5 in the same file so they should show up in consensusTree() as well. Consensus trees from other software (e.g. _ape_ in R) work without issues, so I suspect the issue to be with the function consensusTree() itself.
Here is the code to reproduce the issue:

tt = readTrees("myposterior.posterior.tree.log")
ct = consensusTree(treeTrace(tt, burnin=0), file = "myposterior.con.tre.log")
mcc = mccTree(treeTrace(tt, burnin=0), file = "myposterior.mcc.tre.log")
map = mapTree(treeTrace(tt, burnin=0), file = "myposterior.map.tre.log")

The bug occurs in the Linux version of latest version of RevBayes (v1.2.1). I tried the same code on an older Windows machine that still had RevBayes v1.1.0 installed and the bug did not occur. 

[myposterior.con.tree.log](https://github.com/revbayes/revbayes/files/11806115/myposterior.con.tree.log)
[myposterior.mcc.tre.log](https://github.com/revbayes/revbayes/files/11806116/myposterior.mcc.tre.log)
[myposterior.map.tre.log](https://github.com/revbayes/revbayes/files/11806117/myposterior.map.tre.log)
[myposterior.posterior.tree.log](https://github.com/revbayes/revbayes/files/11806118/myposterior.posterior.tree.log)

**Comment by davidcerny** [comment]
Fixed by PR #441.
