### ISSUE TITLE
[BUG] Alloc Issues with Power Posteriors from Tutorial

### ISSUE THREAD

**Issue by mmyen** [revbayes/revbayes#366]
**Describe the bug**
A few days ago, when I was going through the ["General Introduction to Model selection" tutorial](https://revbayes.github.io/tutorials/model_selection_bayes_factors/bf_intro.html), I got a `std::bad_alloc` error while trying to set up the stepping stone sampling and path sampling code. I did not notice any provided data files and scripts on the page, so I decided to copy and paste in an old model from an earlier tutorial page (["Introduction to MCMC"](https://revbayes.github.io/tutorials/mcmc/poisson.html)). 

My model by itself ran without any issues, so I'm a little confused as to why adding the power posteriors and stepping stone or path sampling methods (I tried both; neither worked) would make my code break.

**To Reproduce**
First, clear the RevBayes workspace (`clear()`) and quit out of RevBayes (`quit()`). Then, run this script (compressed for uploadability):
[bayes_model_sel_2.Rev.zip](https://github.com/revbayes/revbayes/files/12134711/bayes_model_sel_2.Rev.zip)

**Expected behavior**
I expected a marginal likelihood to be printed/shown on the terminal. 

**Screenshots**
I got these screenshots (potentially sensitive information redacted):
<img width="607" alt="Screen Shot 2023-07-21 at 2 06 38 PM" src="https://github.com/revbayes/revbayes/assets/91394943/d1b1b77c-f395-4afa-9801-96d76d0fe174">
<img width="598" alt="Screen Shot 2023-07-21 at 2 03 35 PM" src="https://github.com/revbayes/revbayes/assets/91394943/37ece8f3-3f88-47d7-bef3-f180cad27b8e">

**Computer info**
I am using RevBayes v1.2.1 on a Mac.

**Additional context**
I also noticed that there were some [files](https://github.com/revbayes/revbayes_tutorial/tree/390a3d78ce63dc7c08cb37e172eefff67b61c42d/RB_BayesFactor_Tutorial/scripts) in the tutorial repository that found the power posterior distributions and the stepping-stone and path sampling marginal likelihoods, which is what was described in the ["General Introduction to Model selection" tutorial](https://revbayes.github.io/tutorials/model_selection_bayes_factors/bf_intro.html). Can someone please let me know the reason they're not linked on the page itself?

**Comment by bredelings** [comment]
Hmm... so what is going on here is that both the monitor and the poster posterior are trying to write to the same file at the same time:
```
monitors[1] = mnModel(filename="output/powp_airline_test.out",printgen=10,separator = "	")
monitors[2] = mnScreen(printgen=10, alpha, beta)

pow_p = powerPosterior(mymodel, moves, monitors, "output/powp_airline_test.out",cats=50)
```

Then, we we try and read the file later, it doesn't work.  The file looks like this:
```state	power	likelihood
400	1	-29.0904
500	1	-28.9701
600	1	-28.3464
700	1	-27.8551
800	1	-27.8449
900	1	-28.287
1000	1	-28.2014
a[10]	y[1]	y[2]	y[3]	y[4]	y[5]	y[6]	y[7]	y[8]	y[9]	y[10]
0	-34.98722	-28.99576	-5.991465	3.074941	-0.02144171	23.8415	23.3358	22.8407	22.3562	21.882	21.4178	20.9634	20.5187	20.0834	19.6574	24	25	31	31	22	21	26	20	16	22
10	-34.26248	-28.27102	-5.991465	3.212564	-0.02059174	27.2547	26.6992	26.1551	25.622	25.0998	24.5882	24.0871	23.5962	23.1153	22.6441	24	25	31	31	22	21	26	20	16	22
20	-33.78041	-27.78895	-5.991465	3.137652	-0.0420035	27.8454	26.7	25.6018	24.5487	23.5389	22.5707	21.6422	20.752	19.8984	19.0799	24	25	31	31	22	21	26	20	16	22
30	-35.47366	-29.48219	-5.991465	3.188448	-0.07868933	34.5549	31.9401	29.5231	27.289	25.2239	23.3152	21.5508	19.92	18.4126	17.0193	24	25	31	31	22	21	26	20	16	22
40	-33.75524	-27.76378	-5.991465	3.146227	-0.03466719	27.1732	26.2473	25.353	24.4891	23.6547	22.8487	22.0702	21.3182	20.5918	19.8902	24	25	31	31	22	21	26	20	16	22
50	-34.62392	-28.63246	-5.991465	3.186916	-0.008645069	25.1742	24.9575	24.7426	24.5297	24.3185	24.1092	23.9017	23.6959	23.492	23.2897	24	25	31	31	22	21	26	20	16	22
...
```

**Comment by bredelings** [comment]
Probably we need to give some error messages in `src/core/analysis/mcmc/MarginalLikelihoodEstimator.cpp` if the file doesn't look like we expect it to.
