### ISSUE TITLE
Replace #includes for C headers (e.g. math.h) with C++ headers (e.g. cmath)

### ISSUE THREAD

**Issue by mlandis** [revbayes/revbayes#371]
This issue is not urgent and can be closed if we don't want to address it. The C-style math.h header is apparently deprecated. If it can be done correctly and easily, we should replace C headers with C++ headers for the math library. Regular expressions can probably do the job. One risk is that math.h and cmath have minor differences in implementations that modify argument lists and/or create small (but real) numerical differences in return values.

Links:
https://cplusplus.com/reference/clibrary/
https://stackoverflow.com/questions/37904753/is-math-h-for-c-or-c

Original PR that is tangentially related to this issue:
https://github.com/revbayes/revbayes/pull/368#pullrequestreview-1561565511

**Comment by bredelings** [comment]
We should probably do this.  It doesn't seem very hard.

We should also probably do
* stdio.h -> cstdio
* stddef.h -> cstddef
* stdlib.h -> cstdlib
* ctype.h -> cctype
* assert.h -> cassert
* errno.h -> cerrno
* limits.h -> climits
* float.h -> cfloat
* stdarg.h -> cstdarg
* string.h -> cstring

It should be possible to do using a command like:
``` sh
find .  -name '*.h' -o -name '*.cpp' | xargs sed -i 's/stddef.h/cstddef/'
```
