### ISSUE TITLE
Repository does not have releases

### ISSUE THREAD

**Issue by Anaphory** [revbayes/revbayes#39]
This repository is confusing. Could there be a link to revbayes.archive somewhere prominent?

When I looked first, I thought the following was the issue instead.
> The releases of the repository vanished and were replaced by a very comfort-inducing release called asdftesting. Presumably, there was a stable version 1.0.4 at some point, because such a thing is referenced in the Arch User Repository. (The version history of the repository is very messy overall, so that it's not clear from it either which commit I want to download to get a stable version, either.)
> As scientific software for studies intended to be reproduceable, it would be really nice if not just a new release could be fixed, but also if it was somehow possible to restore the release history.

**Comment by njbooher** [comment]
I can't see a way to make a GitHub release without having a tag, and this repository didn't keep the history from the old one.

I added a tag on the initial commit here with a note and link to the old repository. Does that help?

https://github.com/revbayes/revbayes/releases

**Comment by Anaphory** [comment]
Sounds like a good way around!
