### ISSUE TITLE
Error in readTreeTrace

### ISSUE THREAD

**Issue by spiritu-santi** [revbayes/revbayes#400]
**Describe the bug**
readTreeTrace is generating and error message in rb 1.2.2 compiled from source, it does however run perfectly under the rb executable (1.2.2).

**To Reproduce**
> tree_init_fn = "Master_Resolved_Const.trees"
> treetrace = readTreeTrace(file=tree_init_fn,  burnin=0.0, thinning=1, separator="")

**Screenshots**
![Captura de pantalla 2023-10-25 a la(s) 9 53 22 a m](https://github.com/revbayes/revbayes/assets/44642626/8acf5390-dc53-4f6e-99ab-0cc365f761a8)

**Expected behavior**
Under the rb 1.2.2 executable the command runs smoothly and reads the treetrace.
![Captura de pantalla 2023-10-25 a la(s) 10 02 07 a m](https://github.com/revbayes/revbayes/assets/44642626/2ff6bcb2-5f30-4197-97b0-4e974c49bd43)

**Computer info**
MacBookPro Intel running on Sonoma 14.0.
rb 1.2.2 compiled from source.

**Additional context**
The abnormal behavior appears using the above (and similar) treetrace files. These files have been processed in R and re-written in the same format as produced by monitors. Another (related?) problem appears when using the original treetrace file under the compiled version, which disappears under the rb executable.
I'm guessing there is a problem with indices in the trees.

**Comment by spiritu-santi** [comment]
**Screenshots for Additional context**
rb 1.2.2 compiled from source
![Captura de pantalla 2023-10-25 a la(s) 10 07 54 a m](https://github.com/revbayes/revbayes/assets/44642626/f1eb7de3-a32c-4115-b8c7-a1e512dc6586)

rb 1.2.2 executable
![Captura de pantalla 2023-10-25 a la(s) 10 08 31 a m](https://github.com/revbayes/revbayes/assets/44642626/1dcd15ae-59f1-4ba9-b571-ca3b94cd4f69)

**Comment by bredelings** [comment]
This warning message does not stop the analysis -- it just says that the indices are ignored.  So, if you ignored the warning messages, does the script still work?

Also, were the trees generated under a fossilized birth death process?

**Comment by spiritu-santi** [comment]
Yes, the trees were produced under the FBD process.
Ok, so I can ignore the warnings in the second case, but the problem still remains for the first error message.
![Captura de pantalla 2023-10-25 a la(s) 9 53 22 a m](https://github.com/revbayes/revbayes/assets/44642626/ba772bf1-bb1d-44ce-bc2a-c16faed59a6c)

I forgot to attach the treetrace (here as txt to allow upload).
[Master_Resolved_Const.trees.txt](https://github.com/revbayes/revbayes/files/13170031/Master_Resolved_Const.trees.txt)

**Comment by bredelings** [comment]
Thanks, that should allow one of us to reproduce the issue.

**Comment by bredelings** [comment]
OK, I found the issue.  One of the trees had `index=NA` for a node.

Do you mind if I include your tree trace as a test case in the revbayes repository?  Alternatively, I can make another tree trace with `index=NA` to make sure that this doesn't break in the future.

**Comment by bredelings** [comment]
OK, I found the issue.  One of the trees had `index=NA` for a node.

Do you mind if I include your tree trace as a test case in the revbayes repository?  Alternatively, I can make another tree trace with `index=NA` to make sure that this doesn't break in the future.

**Comment by bredelings** [comment]
Fixed by #403
