### ISSUE TITLE
[BUG] FBD model with sampled ancestors

### ISSUE THREAD

**Issue by hoehna** [revbayes/revbayes#401]
**Describe the bug**
Once a tip is set as a sampled ancestor, then node age moves change the tip age. This should neither happen and leads to strange model behavior.

**To Reproduce**
See attached script. Note that the oldest fossil gets a new age and is stuck at 49, the max origin time.

**Expected behavior**
Fossil tips should not change their age, only if there is a specific fossil 
move.

[test_FBD_dating.zip](https://github.com/revbayes/revbayes/files/13172969/test_FBD_dating.zip)

**Comment by bredelings** [comment]
We talked about this on the call today.

Sample ancestors can either have a fixed age, or can have an age within an interval.  If we try and scale the tree and move a sampled ancestor node outside of its interval, then the tree should have probability 0, effectively blocking all moves that rescale the whole tree.

General consensus was that MCMC moves need to be able to identify sampled ancestor nodes.  Tree scaling moves would need to avoid scaling them, whereas moves that slide the internal node age for a single node could just do nothing.

One solution would be to make setAge( ) throw an exception if a move tries to change the age for a sampled ancestor.

**Comment by bredelings** [comment]
OK, so it looks like mvRootTimeSlideUniform is indeed moving fossils if the root is a sampled ancestor.  This does not appear to be a recent change in behavior though.

**Comment by bredelings** [comment]
Fixed by #447
