### ISSUE TITLE
[BUG] 'no function named geometricMean' 

### ISSUE THREAD

**Issue by JennaMcCullough** [revbayes/revbayes#427]
As apart of a larger script, I'm trying to run this code
Z_w := geometricMean(g_w)

in which g_w is 
> g_w
   [ 0.089, 0.037, 0.000, 0.041, 0.004, 0.007, 0.008, 0.004, 0.059, 0.493, 0.520, 0.055, 10.436, 0.028, 4.166, 0.617 ]

I get the error 
> Z_w := geometricMean(g_w)
   Error:	No function named 'geometricMean'

I know it is a function (https://revbayes.github.io/documentation/geometricMean.html) 

I'm running revbayes v 1.0.12 through conda on a linux machine. 

Do you know what could be causing this issue? 

<img width="766" alt="Screen Shot 2024-01-31 at 9 56 35 AM" src="https://github.com/revbayes/revbayes/assets/8632718/5b427a52-6819-4f5d-a94c-315b4c4eb091">

**Comment by davidcerny** [comment]
Hi @JennaMcCullough, sorry to hear you're experiencing problems with your Rev code!

I can no longer reproduce this issue using the latest stable release (v1.2.2; 4fef47c) or the latest version of the `development` branch (rapture-2386-g54c6ba), both of which give me the expected output:

```
> g_w <- [ 0.089, 0.037, 0.000, 0.041, 0.004, 0.007, 0.008, 0.004, 0.059, 0.493, 0.520, 0.055, 10.436, 0.028, 4.166, 0.617 ]
> Z_w := geometricMean(g_w)
> Z_w
   0
```

Therefore, I'd suggest simply switching to a more recent version of RevBayes – v1.0.12 is very old anyway.

**Comment by JennaMcCullough** [comment]
I found out later that for this program, I needed a specific branch of Revbayes, the Hawaii_fix branch. In case anyone receives this error in the future, for the record the program I'm trying to run is Michael Landis' feature informed geographic model (FIG) https://www.pnas.org/doi/10.1073/pnas.2116948119
