### ISSUE TITLE
Double condition in demographic functions

### ISSUE THREAD

**Issue by rbillenstein** [revbayes/revbayes#45]
Hi,

I found a double condition in an if statement in the exponential and linear demographic functions:
`if ( t1 < t0 || t0 < 0 || N1 < 0 || N1 < 0 || start < t0 || start > t1 || finish < t0 || finish > t1 )`
The condition `N1 < 0` is used twice, this if statement is in two lines in each of the files.
The files are ExponentialDemographicFunction.cpp and LinearDemographicFunction.cpp in core//distributions/phylogenetics/tree/coalescent/demography/ , I added a `@todo` there in the doxygen documentation, so the lines should be easy to find.

Ronja

**Comment by hoehna** [comment]
Feel free to modify to the code accordingly. There could be other simplifications, for example: if start > t0 and start < t1 it follows that t1 > t0, so the very first check is not necessary. However, personally I would keep these in there for readability of all checks (less logical thinking required) and those checks are really not time consuming. Nevertheless, duplicated checks are unnecessary.

**Comment by rbillenstein** [comment]
Thank you, I just removed the duplicated condition now.
