### ISSUE TITLE
[BUG] Error Occurs During Type Conversion in seq Function When 0 is Included

### ISSUE THREAD

**Issue by minghao-du** [revbayes/revbayes#464]
**Describe the bug**
When there is a `0` in `seq`, an error occurs during type conversion: `Error: Failed conversion from type 'Integer' to type 'RealPos'`.

**To Reproduce**
`0.1 * seq(1, 99, 1)` runs normally, but running `0.1 * seq(0, 99, 1)` prompts an error: `Error:  Failed conversion from type 'Integer' to type 'RealPos'`. I guess it's because the vector contains 0.

PS: `0.1 * seq(0.0, 99, 1)` also runs normally.

**Expected behavior**
`0.1 * seq(0, 99, 1)` can run normally.

**Screenshots**
<img width="1114" alt="image" src="https://github.com/revbayes/revbayes/assets/51898298/ad187670-799c-4f8e-bbbf-78e54c4f50a0">

**Computer info**
I am using a Mac, and the version of RevBayes I am using is development (rapture-2545-g7c2b56).

**Comment by davidcerny** [comment]
Fixed by #554.
