### ISSUE TITLE
parsing the parameters in the monitor log file

### ISSUE THREAD

**Issue by chlangley** [revbayes/revbayes#478]
Hello:
Now that Skyfish is digesting my data and yielding Skyfish flavored Skylines of Ne and trees, I am turning to check convergence and estimates of parameters.

But the 'log' file with all the parameter values at each thinning iteration created by 
`monitors.append( mnModel(filename="output/mcmc_isochronous_SkyfishAC.log",printgen=THINNING) )`
 is difficult to parse since the numbers of changePoints, interval_times and population_sizes are variable.  

Segregating these variable parameters into their own log files might be a solution? Is there a familiar, rb-elegant solution?

As an immediate hack, I'd code up a script to post-process this 'standard' monitor log file into one file with the fixed number of parameters and dump the variable ones into a second file.  Or one might specify mnFile() for each parameter? Cumbersome.

So before starting, I thought I'd ask if the authors of Skyfish (R.B. and S.H.) or another user might not have a solution/tool in hand to share.

Cheers,
Chuck

**Comment by bredelings** [comment]
This isn't a solution to your problem, but note that you can add `format="json"` and get log files in JSON format.  Perhaps that will be some help in writing a script to post-process the results.  Also see https://github.com/bredelings/MCON

**Comment by bredelings** [comment]
I think I recall @hoehna saying that they printed the variables with variable-dimension to a different file for each variable.  I'd be curious to hear @hoehna and @rbillenstein how they handled this in practice.

**Comment by bredelings** [comment]
BTW, I've update `mcon-tool` from the MCON repo above so that it now actually does drop variable-dimension fields when converting from JSON to TSV.

**Comment by rbillenstein** [comment]
Dear Chuck,

happy to hear that the Skyfish analysis is now working for you.

You can exclude the variable parameters from the Model monitor.
```
to_exclude = v("population_size", "interval_times", "changePoints")

monitors.append( mnModel(filename="output/mcmc_isochronous_SkyfishAC.log", exclude=to_exclude, printgen=THINNING) )
```

We usually add separate log files for the variable parameters using `mnFile()` as you suggested.
The whole set of monitors might look like this, depending on what you need:
```
monitors.append( mnModel(filename="output/mcmc_isochronous_SkyfishAC.log", exclude = to_exclude, printgen=THINNING) )
monitors.append( mnFile(filename="output/mcmc_isochronous_SkyfishAC.trees",psi,printgen=THINNING) )
monitors.append( mnFile(filename="output/mcmc_isochronous_SkyfishAC_NEs.log",population_size,printgen=THINNING) )
monitors.append( mnFile(filename="output/mcmc_isochronous_SkyfishAC_times.log",interval_times,printgen=THINNING) )
```

If you are plotting your results with `RevGadgets`, the input would be the log file of the population size and the log file of the interval times.
```
population_size_log = "output/mcmc_isochronous_SkyfishAC_NEs.log"
interval_change_points_log = "output/mcmc_isochronous_SkyfishAC_times.log"

df = processPopSizes(population_size_log, interval_change_points_log)
plotPopSizes(df)
```

You can also check convergence of the population size estimates by comparing the distributions between MCMC replicates at different time points (https://revbayes.github.io/tutorials/coalescent/postprocessing).
In the case of two replicates it might look like this:

```
population_size_log_run1 = "output/mcmc_isochronous_SkyfishAC_NEs_run_1.log"
interval_change_points_log_run1 = "output/mcmc_isochronous_SkyfishAC_times_run_1.log"

population_size_log_run2 = "output/mcmc_isochronous_SkyfishAC_NEs_run_2.log"
interval_change_points_log_run2 = "output/mcmc_isochronous_SkyfishAC_times_run_2.log"

df_1 = processPopSizes(population_size_log_run1, interval_change_points_log_run1, distribution = TRUE)
df_2 = processPopSizes(population_size_log_run2, interval_change_points_log_run2, distribution = TRUE)

ks_data = matrix(nrow = dim(df_1)[1], ncol = 2)
ks_data[,1] = as.numeric(rownames(df_1))
for (i in 1:dim(df_1)[1]){
  ks_data[i,2] = ks.test(df_1[i,], df_2[i,])$statistic
}

plot(ks_data)
abline(h=0.0921)
```

I hope this is helpful.

Best regards,
Ronja

**Comment by davidcerny** [comment]
Closing this issue as resolved, but please feel free to reopen it @chlangley if there any additional problems or follow-up questions!
