### ISSUE TITLE
[BUG] Significant Fossil Age Estimation Errors When Using Checkpoint in FBD Model Analysis

### ISSUE THREAD

**Issue by minghao-du** [revbayes/revbayes#482]
**Describe the bug**
When using the FBD model for phylogenetic inference, continuing the analysis with Checkpoint leads to significant changes in the inferred fossil ages, even erroneous changes.

**To Reproduce**
In the tutorial "Combined-Evidence Analysis and the Fossilized Birth-Death Process for Analysis of Extant Taxa and Fossil Specimens," simply add Checkpoint to the script.

All scripts and output are in this file.
[revbayes_fbd_fbd_specimen_checkpoint.zip](https://github.com/user-attachments/files/15970289/revbayes_fbd_fbd_specimen_checkpoint.zip)

**Expected behavior**
Continuing the previous analysis using Checkpoint should not produce anomalous results.

**Screenshots**
<img width="1177" alt="image" src="https://github.com/revbayes/revbayes/assets/51898298/ada528ac-28fd-4233-aa73-08ec97298acd">
This is a computational result: I ran for 5000 iterations, then used Checkpoint to run another 5000 iterations, and then used Checkpoint again at 10000 iterations to run another 5000 iterations. It seems that every time Checkpoint is used, the fossil ages change significantly, with the age estimates even being 0 between 5000-10000 iterations. All fossil ages have this problem.

**Computer info**
I am using a Mac, and the version of RevBayes I am using is development (rapture-2776-g62de34).

**Additional context**
Perhaps checking the tree log files before and after using Checkpoint might help identify where the problem occurs.

**Comment by bjoelle** [comment]
should be fixed by PR #484
