### ISSUE TITLE
[BUG] MCMC Stops After 200 Iterations When Using Checkpoint with FBD Model and Mass Extinction in version 1.2.4

### ISSUE THREAD

**Issue by minghao-du** [revbayes/revbayes#483]
**Describe the bug**
When performing phylogenetic inference using an FBD model with mass extinction, after using a checkpoint, the MCMC only continues for 200 iterations and then stops.

**To Reproduce**
The data and code I used are in this file. Simply run the _scripts/FBD_Model.Rev_ file.
[FBD_Checkpoint.zip](https://github.com/user-attachments/files/15983631/FBD_Checkpoint.zip)

I am attempting to conduct phylogenetic inference using both molecular and morphological data (total evidence dating). While using the FBD model as the tree prior, I also included mass extinction. I fixed the mass extinction time at 30 but inferred the probability of mass extinction.

**Expected behavior**
After using the checkpoint to continue the analysis, it should run normally instead of stopping after 200 iterations.

**Screenshots**
<img width="468" alt="image" src="https://github.com/revbayes/revbayes/assets/51898298/933d0060-cd6a-414d-9606-2197f0e50dbc">

When continuing the analysis using the checkpoint, it stops at this screen and does not proceed with further iterations.

**Computer info**
I am using a Mac, and the version of RevBayes I am using is development (rapture-2776-g62de34).

**Additional context**
1. This issue seems to occur only in version 1.2.4. When I used version 1.2.2 (development, rapture-2545-g7c2b56), this issue did not occur.
2. On one occasion, after continuing the run, the Posterior and Likelihood values for iterations 1100 and 1200 were -inf, but I could not reproduce this result. Is it possible that the program is still running, but abnormal Posterior and Likelihood values are causing each iteration to take a very long time?

**Comment by bjoelle** [comment]
so the problem appears to be that the move `FossilTipTimesSlide` gets stuck because the fossil age ranges are not restored properly when initializing from checkpoint
I don't understand why this didn't happen in 1.2.2 but it's possible that it was masked by another bug

**Comment by bjoelle** [comment]
should be resolved by PR #484
