### ISSUE TITLE
[Help Wanted] Boost issues when installing RevBayes from source

### ISSUE THREAD

**Issue by ms609** [revbayes/revbayes#489]
**Describe the desired behavior.**
RevBayes is installed from source, using VSCode

**What is going wrong?**
I see
```
[main] Configuring project: revbayes-ms 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.exe" --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -SC:/Users/<username>/GitHub/revbayes-ms/src -Bc:/Users/<username>/GitHub/revbayes-ms/build -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] Boost location hints:
[cmake]   BOOST_ROOT not set
[cmake] Searching for BOOST:
[cmake] CMake Error at CMakeLists.txt:155 (find_package):
[cmake]   By not providing "FindBoost.cmake" in CMAKE_MODULE_PATH this project has
[cmake]   asked CMake to find a package configuration file provided by "Boost", but
[cmake]   CMake did not find one.
[cmake] 
[cmake]   Could not find a package configuration file provided by "Boost" (requested
[cmake]   version 1.71.0) with any of the following names:
[cmake] 
[cmake]     BoostConfig.cmake
[cmake]     boost-config.cmake
[cmake] 
[cmake]   Add the installation prefix of "Boost" to CMAKE_PREFIX_PATH or set
[cmake]   "Boost_DIR" to a directory containing one of the above files.  If "Boost"
[cmake]   provides a separate development package or SDK, be sure it has been
[cmake]   installed.
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
```

I've added `SET(CMAKE_TOOLCHAIN_FILE "C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake" CACHE STRING "Vcpkg toolchain file")` after `project(RevBayes)` in the `CMakeLists.txt` file.

**Anything else you've tried?**
I've followed the [documentation](https://revbayes.github.io/developer/setup/#configure-the-cc-build-settings).

I've tried a few dozen things, one of which seemed to work briefly, until I deleted the `build` subdirectory to address a later issue.  I think I was successful with something like
```
SET(BOOST_ROOT "C:/boost/boost_1_85_0")
SET(Boost_DIR "C:/boost/boost_1_85_0")
SET(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "C:/boost/boost_1_85_0")
SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "C:/boost/boost_1_85_0")
SET(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} "C:/boost/boost_1_85_0/boost")
SET(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} "C:/boost/boost_1_85_0/boost/lib")
```
but I can't replicate that success now!

**Computer info**
Windows 10; RevBayes development branch.

I've updated from VS2019 to VS 2022, and from cmake 3.20 to cmake 3.30.
I've installed Boost using vcpkg.  I also tried downloading the Boost files and installing to c:/boost, but couldn't work out how to build these.

Sorry if I'm missing something simple, I'm not very experienced with building C++projects!

**Comment by bjoelle** [comment]
Hello Martin,
For me what worked was to add the BOOST_ROOT setting directly into `settings.json`
```
"cmake.configureArgs": [
        "-DBOOST_ROOT=C:\\Users\\barid\\Work\\Software\\boost_1_82_0"
], ```

**Comment by ms609** [comment]
Thanks.   I've made some progress and resolved the Boost issue.  The necessary steps:

1. Download Boost and unzip.  I chose to unzip v1.85.0 to `c:\boost\boost_1_85_0`.
2. Download [b2 5.2.0](https://github.com/bfgroup/b2/releases) or above.  b2 v5.1.0, bundled with Boost, is [not compatible](https://github.com/conan-io/conan/issues/16465) with msvc-14.3.
2. Use the "x64 Native Tools Command Prompt for VS 2022" to `cd` to the boost directory, for me: `c:/boost/boost_1_85_0`
3. Execute `bootstrap.bat`
4. Remove (or rename) `b2.exe`.
4. Run `b2 --version` to confirm that a version of b2 >= 5.2 is available
4. Execute `b2 address-model=64 architecture=x86 toolset=msvc-14.3 --build-dir=build --build-type=complete --prefix=c:/boost/boost_1_85_0/inst --with-regex --with-program_options --with-thread --with-system --with-filesystem --with-date_time --with-serialization  install`
5. Verify that `C:\boost\boost_1_85_0\inst\lib\cmake\Boost-1.85.0` contains `BoostConfig.cmake`
6. Add `set(Boost_COMPILER "-vc143")` and `set(BOOST_ROOT "C:/boost/boost_1_85_0/inst")` to `CMakeLists.txt`, after the `project(RevBayes)` line.


I now see:

```
[cmake] CMake Error at CMakeLists.txt:171 (include):
[cmake]   include could not find requested file:
[cmake] 
[cmake]     generated_include_dirs
[cmake] 
[cmake] 
[cmake] CMake Error at CMakeLists.txt:174 (add_subdirectory):
[cmake]   The source directory
[cmake] 
[cmake]     C:/Users/<username>/revbayes/src/libs
[cmake] 
[cmake]   does not contain a CMakeLists.txt file.
```
(and the same for `src/core` and `src/revlanguage`).

If I comment out the `include` and `add_subdirectory` lines, then I see:


```
[cmake] CMake Error:
[cmake]   Running
[cmake] 
[cmake]    'C:/Strawberry/c/bin/ninja.exe' '-C' 'C:/Users/<username>/revbayes/build' '-t' 'recompact'
[cmake] 
[cmake]   failed with:
[cmake] 
[cmake]    ninja: error: build.ninja:148: multiple rules generate ../rb.exe
```

**Comment by ms609** [comment]
I've been learning a lot about makefiles whilst exploring this issue!  This latter issue seems to have arisen because I used an MSVC compiler to install Boost.  I'm going to have another crack using gcc throughout.  

Once I've got things working, it might be useful to add instructions for installing and configuring Boost at https://revbayes.github.io/developer/setup/.  I'm happy to propose some changes in a pull request based on what I think worked for me, though this task might be better performed by someone who knows what they are doing!

**Comment by ms609** [comment]
I've now put these instructions together at https://github.com/revbayes/revbayes.github.io/pull/30, and separately have suggested some pull requests that address some of the issues and blind alleys I encountered whilst working through CMakeLists.txt.
