### ISSUE TITLE
Conflicting monophyletic clade constraints

### ISSUE THREAD

**Issue by NickCrouch** [revbayes/revbayes#5]
Hi,
There appears to be a problem with designating nested clade constraints. I encounter this problem when analyzing the exemplar bears data. In the tutorial a single clade constraint is defined:
`clade_ursinae = clade("Helarctos_malayanus", "Melursus_ursinus", "Ursus_abstrusus", "Ursus_americanus", "Ursus_arctos", "Ursus_maritimus",   "Ursus_thibetanus")`
which works find. If a second constraint is specified and then enforced, then the error is returned
`clade_ursus = clade("Ursus_abstrusus","Ursus_thibetanus")`
`constraints = v(clade_ursinae, clade_ursus)`

> Error: Cannot simulate tree: conflicting monophyletic clade constraints. Check that all clade constraints are properly nested.

This error derives from the error checks `found_some` and `found_all` in "TopologyConstrainedTreeDistribution.cpp" but I'm not sure how. 

I replicated this issue using the recently pushed "oh, rapture" update.

**Comment by ziad-khouri** [comment]
Can confirm that this is still an issue as of commit 11f057bb037e5dc54a246688f36c5a9e880a0daa development branch.

**Comment by bredelings** [comment]
OK, this issue is easy to reproduce by adding the ` clade_ursus = clade("Ursus_abstrusus","Ursus_thibetanus")` constraint in `model_FBDRP.Rev`, as mentioned above.

The issue occurs when simulating the initial tree.  This happens in`TopologyConstrainedTreeDistribution::simulateTree( void )` in `/src/core/distributions/phylogenetics/tree/TopologyConstrainedTreeDistribution.cpp`.  

Interestingly, if you switch the order of the two clades from ` constraints = v(clade_ursinae, clade_ursus)` to `constraints = v(clade_ursus, clade_ursinae)`, then we get:
```
> source("mcmc_CEFBDRP_Ranges.Rev")
   Processing file "mcmc_CEFBDRP_Ranges.Rev"
   Successfully read one character matrix from file 'data/bears_cytb.nex'
   Successfully read one character matrix from file 'data/bears_morphology.nex'
   Processing file "scripts/model_FBDRP.Rev"
   Processing of file "scripts/model_FBDRP.Rev" completed
   Processing file "scripts/model_UExp.Rev"
   Processing of file "scripts/model_UExp.Rev" completed
   Processing file "scripts/model_GTRG.Rev"
   Processing of file "scripts/model_GTRG.Rev" completed
   Processing file "scripts/model_Morph.Rev"
   Processing of file "scripts/model_Morph.Rev" completed
   Could not compute lnProb for node fbd_tree.
   (((((Arctodus_simus[&index=22]:32.636742,((Kretzoia...

rb: ../../source/src/core/distributions/phylogenetics/substitution/PhyloCTMCSiteHomogeneous.h:258: void RevBayesCore::PhyloCTMCSiteHomogeneous<charType>::computeInternalNodeLikelihood(const RevBayesCore::TopologyNode&, size_t, size_t, size_t) [with charType = RevBayesCore::StandardState; size_t = long unsigned int]: Assertion `0.0 <= sum and sum <= 1.00000000001' failed.
Aborted
```

**Comment by NickCrouch** [comment]
I'm still running into this issue with an empirical data set using the 1.1.1 Windows release. 

Attached is data for 6 species from our data showing one example of the. Modifying the `model_FBDRP` script to including the second constraint causes the conflicting monophyletic constraints error, even though it is a clear subset of the wider constraint. 

> clade_crown = clade("Taxon_b", "Taxon_c", "Taxon_d", "Taxon_e", "Taxon_f")
> clade_1 = clade("Taxon_c", "Taxon_d", "Taxon_e", "Taxon_f")
> constraints = v(clade_crown, clade_1)

[rb_example.zip](https://github.com/revbayes/revbayes/files/6528906/rb_example.zip)
