### ISSUE TITLE
regenerate.sh makes it hard to pass options to cmake

### ISSUE THREAD

**Issue by bredelings** [revbayes/revbayes#51]
CMake accepts options.  We could easily select different compiler flags for debug builds inside cmake by passing an option, but that is hard because currently we use options to _generate_ CMakeLists.txt, and then pass no options to cmake.

We should stop generating the main CMakeLists.txt from regenerate.sh, and instead pass options into cmake.  We should make it easier to pass options to cmake from `build.sh`.  (We will still need to generate CMakeLists.txt for subdirectories:
`find libs | grep -v "svn" | sed 's|^|${PROJECT_SOURCE_DIR}/|g' >> "$BUILD_DIR/libs/CMakeLists.txt"
`

**Comment by bjoelle** [comment]
@bredelings was that issue solved by PR #54 or are you still working on it ?

**Comment by bredelings** [comment]
Yeah, this was solved by PR #54
