### ISSUE TITLE
[BUG] Reading and clamping PoMo data produces std::bad_alloc error

### ISSUE THREAD

**Issue by MolZoo** [revbayes/revbayes#546]
**Describe the bug**
As I follow along the _Polymorphism-aware phylogenetic models_ tutorial (https://revbayes.github.io/tutorials/pomos/), I fail to read the count file _data/great_apes_1000.cf_.

```
> data <- readPoMoCountFile("great_apes_1000.cf", virtualPopulationSize=3)
POSITION: 41275799
State: 6,0,0,0
stringvalue: 6,0,0,0
1 1e-08 1e-08 1e-08 0.00137174 0.0877915 0.00137174 0.0877915 0.00137174 0.0877915 1e-08 1e-08 1e-08 1e-08 1e-08 1e-08 

 
   std::bad_alloc

```

A similar error occurs when I bypass reading the count file by using a fasta file. As _data/individual_sequences.nex_ is not provided in the tutorial, I tried to use my own sequence data. When I try to clamp the data to my model (set up exactly the same way as described in the tutorial), I am advised that once again a memory allocation error occurred. However, calling "sequences" shows me that the data has been successfully clamped. 
```
> sequences
   
    character matrix with 12 taxa and 0 characters
   ===============================================
   Origination:                   ""
   Number of taxa:                12
   Number of included taxa:       12
   Number of characters:          0
   Number of included characters: 0
   Datatype:                      
   
> sequences.clamp(data)
   std::bad_alloc
> sequences
   
   PoMo character matrix with 12 taxa and 106 characters
   =====================================================
   Origination:                   ""
   Number of taxa:                12
   Number of included taxa:       12
   Number of characters:          106
   Number of included characters: 106
   Datatype:                      PoMo

```
Yet, if I call the model, I am shown that no clamping occurred:
```
   sequences :
   _value        = PoMo character matrix with 12 taxa and 106 characte..
   _dagType      = Stochastic node (distribution)
   _distribution = dnPhyloCTMC(Tree<any> tree, RateGenerator|RateGenerator[]|SiteMixtureModel<any> Q, Simplex<any> rootFrequencies, RealPos|RealPos[]<any>
   branchRates, Simplex|Bool<any> siteMatrices, RealPos[]<any> siteRates, Simplex<any> siteRatesProbs, Probability<any> pInv, Natural<any> nSites, String<any>
   type {valid options: "DNA"|"RNA"|"AA"|"Codon"|"Doublet"|"PoMo"|"Protein"|"Standard"|"NaturalNumbers"|"Binary"|"Restriction"}, Bool<any> treatAmbiguousAsGap,
   String<any> coding, Bool<any> storeInternalNodes, Bool<any> gapMatchClamped)
   _clamped      = FALSE
   _lnProb       = -4455.43
   _parents      = [ psi, sequences.branchRates, Q ]
   _children     = [  ]
```

**To Reproduce**
The error can simply be reproduced by following along the [tutorial](https://revbayes.github.io/tutorials/pomos/).

**Expected behavior**
The file should be read in.

**Computer info**
I reproduced this error with multiple versions of RevBayes (1.2.5 compiled from source, 1.2.4 from executable and singularity, 1.1.0 from singularity) on a Linux (Ubuntu 22.04.4 LTS) and Windows (11) machine. I don't think that the error is linked to my machine, as I should have enough RAM to run the revBayes tutorial:

```
free -h
               gesamt       benutzt     frei      gemns.  Puffer/Cache verfügbar
Speicher:       60Gi       6,2Gi        43Gi       262Mi        11Gi        53Gi
Auslager:      2,0Gi          0B       2,0Gi
```

Thanks ever so much for your help,
All the best,
Paul

**Comment by davidcerny** [comment]
Apologies for the late reply @MolZoo. The PoMo tutorial is intended to be run on an in-development version of RevBayes that you can compile from the [`dev_PoMo_SNP`](https://github.com/revbayes/revbayes/tree/dev_PoMo_SNP) branch; the key features are not yet available in the latest stable release. The tutorial has now been updated to make this clear.

Closing this issue for now, but please feel free to re-open it or create a new one if you encounter any other related bugs.
