### ISSUE TITLE
Drifting fossils with dnFBDP and sampled ancestors

### ISSUE THREAD

**Issue by Jeremy-Andreoletti** [revbayes/revbayes#57]
When testing the fossilized birth-death process distribution without taking into account the fossil age uncertainty (so without the `mvFossilTimeSlideUniform` move) I expected fossils to stay fixed in time. However some of them were drifting towards the past when I allowed for the presence of sampled ancestors (with the `mvCollapseExpandFossilBranch` move).

Here are some reproducible examples based on the testing script provided for the FBDP (cannot be attached here but I can send it if you want). In each case I compared with or without sampled ancestors to check if they kept their age:
![dnFBDRP](https://user-images.githubusercontent.com/45073058/77686270-f5582f80-6f9c-11ea-95d3-1872b137fb9d.png)

![dnFBDP](https://user-images.githubusercontent.com/45073058/77686274-f721f300-6f9c-11ea-9d3d-c17f1b4d8821.png)

![dnFBDP_noNodeSliding](https://user-images.githubusercontent.com/45073058/77686275-f7ba8980-6f9c-11ea-80b0-f1a7ffd7f0f5.png)

As you can see, with `dnFBDRP` it worked perfectly well, with `dnFBDP` it did not (all fossils at the root), but when I removed the `mvNodeTimeSlideUniform` move it functioned much better again except for 2 taxa which were still shifted. Do you have any idea of what might be causing this strange behavior?

I have been advised to post it here because this problem may be of interest to several people, but I may be misunderstanding something important, so please let me know if that's the case!

**Comment by willpett** [comment]
Hi Jeremy,

I believe your issue is caused by a bug of `mvNodeTimeSlideUniform` that allows it to consider sampled ancestors as internal nodes. I have fixed this on the `fbd` branch, and now I don't see drifting ages.

However, I am still not able to reproduce the issue you had with 2 taxa drifting even without `mvNodeTimeSlideUniform`. After about how many generations does this happen?

**Comment by Jeremy-Andreoletti** [comment]
Hi Will, thanks for your answer,
It makes perfect sense, there was clearly a bug with `mvNodeTimeSlideUniform` and sampled ancestors, so it's great that you solved it!
The other bug seems weirder to me as well. There are no sliding sampled ancestors, but in this case, Indarctos arctoides and Inarctos pujabiensis are moved at one point in the MCMC.
With this script and the bear dataset, you should reproduce the problem in 20 seconds : [mcmc_FBDP.txt](https://github.com/revbayes/revbayes/files/4531123/mcmc_FBDP.txt)

**Comment by willpett** [comment]
I can't reproduce this small issue with Indarctos using the latest code on the fbd branch.
