### ISSUE TITLE
meson build on ubuntu boost installation.

### ISSUE THREAD

**Issue by mtholder** [revbayes/revbayes#74]
On a server running ubuntu 18.04, I needed to run `sudo apt-get install libboost-all-dev` instead of `sudo apt-get install libboost-dev` instruction in https://github.com/revbayes/revbayes/blame/development/projects/meson/README.md#L19

I would submit a PR, but I don't know if libboost-all-dev is needed just for ubuntu or for both ubuntu and debian

**Comment by bredelings** [comment]
I think that's right on debian too, my mistake.

**Comment by bredelings** [comment]
Fixed.
