### ISSUE TITLE
Large positive log likelihoods running discrete character matrix

### ISSUE THREAD

**Issue by zhangchicool** [revbayes/revbayes#84]
I tested two discrete character matrixes, the first seems fine (test1), but  I notice that some numbers are reported incorrectly which makes me a bit worried (see test1/output_nonclock/disc_Mkv.screen.txt). RevBayes reported 46 binary characters but there are actually 43. It reported 3 characters incompatible with the specified coding bias, but there are 5 in the data. See also #83 for the consensus tree issue.

For the other dataset (test2), RevBayes produced large positive log likelihoods and both likelihoods are inconsistent (test2/output_nonclock/disc_*). I wonder the likelihood calculation of the Mk model might contain some bugs.

I also include MrBayes runs as a reference (mb-nonclock/*).
I compiled the code from source in the master branch (I tried the pre-compiled version 1.1.0 too).  My system is macOS Catalina (10.15.6) with Xcode 11.6 and Apple clang version 11.0.3. I installed cmake and boost using the latest homebrew. I hope the attached files are sufficient to  reproduce the described phenomena. If you need anything more let me know. Thanks.

[tests-disc.zip](https://github.com/revbayes/revbayes/files/5004561/tests-disc.zip)

**Comment by bjoelle** [comment]
@zhangchicool I have looked into your problem with the test1 dataset
it appears that `setNumStatesPartition` includes characters based on the maximum state present, meaning that characters which are all 1s will be included as "binary", while characters which are all 0s are not
there are 3 "all 1" characters in your alignment, which is what gives the number of 46 
similarly, RevBayes reports only the incompatible characters which are included, so it reports the 3 "all 1" but not the 2 "all 0"
I will open an issue to fix the behaviour of `setNumStatesPartition`, but the alignment itself is properly handled

**Comment by wrightaprilm** [comment]
I've encountered the issue of the large positive likelihoods. I think it might be something with the initialization of the Mk - it doesn't occur every time. I'll do some testing later in the week.

**Comment by zhangchicool** [comment]
> I've encountered the issue of the large positive likelihoods. I think it might be something with the initialization of the Mk - it doesn't occur every time. I'll do some testing later in the week.

The initial log likelihood is negative, then goes up quickly, e.g., from the 10th iteration.

**Comment by willpett** [comment]
This looks like an issue that pops up when using both ambiguous characters, and partitioning by state number. See #90

**Comment by willpett** [comment]
My manual count of binary characters in test1 gives 46. There are 2 characters that are constant state 0, which do not count binary characters according to the criteria for setNumStatesPartition (they are unary). Therefore, these 2 characters are not included when counting incompatible characters in the binary partition, hence the total of 3 incompatible characters.
