### ISSUE TITLE
Uninformative exception with screen monitor

### ISSUE THREAD

**Issue by wadedismukes** [revbayes/revbayes#96]
While running a Fossilized-Birth-Death-Process analysis, I accidentally set the number of generations of the screen monitor 0. This results in this exception: `Floating point exception: 8` following the printout of the screen monitor header.

The following files replicate the issue if you run `rb mcmc_CEFBDP_Specimens.Rev`. 
[screen_exception_issue.tar.gz](https://github.com/revbayes/revbayes/files/5119411/screen_exception_issue.tar.gz)

Since this is quite cryptic I think if a user sets the number of generations like this: 

`monitors.append(mnScreen(printgen=0, num_samp_anc, origin_time))`

It should print something like:
`The generations was set 0 which isn't allowed`

**Comment by willpett** [comment]
Fixed in #98
