### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by sdwfrost** [revbayes/revbayes#98]
.```/build.sh``` throws the following error:

```
 CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1202 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.55.0

  Boost include path: /home/simon/Programs/revbayes/boost_1_55_0

  The following Boost libraries could not be found:

          boost_iostreams
```

I get the same problem on two separate distributions (Mint Linux 13 and 17); I do have boost 1.55 headers installed at /usr too.

**Comment by hoehna** [comment]
We could reproduce the error on a virtual box using Mint. Apparently you are missing some dependencies for boost to compile. This should do the trick:

sudo apt-get install libbz2-dev

**Comment by sdwfrost** [comment]
Thanks, this fixed it - I'm surprised that installing libboost1.55-all-dev from the Ubuntu packages didn't pull in all dependencies.
