### ISSUE TITLE
setwd() not working - RevBayes version 1.0.0 beta 2 (2015-07-14) on Bio-Linux 8.0.7

### ISSUE THREAD

**Issue by lcscs12345** [revbayes/revbayes#99]
Hi,

I'm using RevBayes version 1.0.0 beta 2 (2015-07-14) on Bio-Linux 8.0.7. There is a bug in setwd(). The only "working" directory is the current directory. Thank you!

`getwd()`
   "/home/manager"
`setwd("/home/manager/misc")`
`getwd()`
   "/home/manager//home/manager/misc"
`setwd("/home/manager/src/revbayes/tests")`
`getwd()`
   "/home/manager//home/manager/misc//home/manager/src/revbayes/tests"
`source("basics.Rev")`
   Error:       Could not open file "basics.Rev"

**Comment by willpett** [comment]
bug confirmed present in development branch. fixed in commit 551fa7d

**Comment by willpett** [comment]
fixed in master with commit 7878f60
